kind: Button
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: button-1
  namespace: krateo-system
spec:
  widgetData:
    label: button 1
    icon: fa-sun
    type: primary
---
kind: PieChart
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: my-pie-chart
  namespace: krateo-system
spec:
  widgetData:
    title: My Panel
    description: This is a description
    total: 100
    data:
      - color: blue
        value: 10
        label: Blue
      - color: darkBlue
        value: 20
        label: Dark Blue
      - color: orange
        value: 30
        label: Orange
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: my-panel
  namespace: krateo-system
spec:
  widgetData:
    title: My Panel
    items:
      - backendEndpointId: my-pie-chart-backend-endpoint-id
      - backendEndpointId: my-table-backend-endpoint-id
  backendEndpoints:
    - id: my-table-backend-endpoint-id
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: my-table
      namespace: krateo-system
      resource: tables
      verb: GET
    - id: my-pie-chart-backend-endpoint-id
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: my-pie-chart
      namespace: krateo-system
      resource: piecharts
      verb: GET
