---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: my-panel
  namespace: krateo-system
spec:
  widgetData:
    title: My Panel
    items:
      - resourceRefId: my-pie-chart
      - resourceRefId: my-table
    tooltip: this is a tooltip!
    footer:
      items:
        - resourceRefId: button-1
        - resourceRefId: button-1
  resourcesRefs:
    - id: my-table
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: my-table
      namespace: krateo-system
      resource: tables
      verb: GET
    - id: my-pie-chart
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: my-pie-chart
      namespace: krateo-system
      resource: piecharts
      verb: GET
    - id: button-1
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: button-1
      namespace: krateo-system
      resource: buttons
      verb: GET
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: panel-with-row
  namespace: krateo-system
spec:
  widgetData:
    title: Panel with Row
    items:
      - resourceRefId: first-row
  resourcesRefs:
    - id: first-row
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: first-row
      namespace: krateo-system
      resource: rows
      verb: GET
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: panel-with-column
  namespace: krateo-system
spec:
  widgetData:
    title: Panel with Column
    items:
      - resourceRefId: first-column
  resourcesRefs:
    - id: first-column
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: first-column
      namespace: krateo-system
      resource: columns
      verb: GET
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: panel-paragraph
  namespace: krateo-system
spec:
  widgetData:
    title: Paragraph
    items:
      - resourceRefId: my-paragraph
  resourcesRefs:
    - id: my-paragraph
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: my-paragraph
      namespace: krateo-system
      resource: paragraphs
      verb: GET
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: panel-yaml-viewer
  namespace: krateo-system
spec:
  widgetData:
    title: Yaml Viewer
    items:
      - resourceRefId: my-yaml-viewer
  resourcesRefs:
    - id: my-yaml-viewer
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: my-yaml-viewer
      namespace: krateo-system
      resource: yamlviewers
      verb: GET
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: panel-event-list
  namespace: krateo-system
spec:
  widgetData:
    title: Event list
    items:
      - resourceRefId: my-event-list
  resourcesRefs:
    - id: my-event-list
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: my-event-list
      namespace: krateo-system
      resource: eventlists
      verb: GET
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: panel-tab-list
  namespace: krateo-system
spec:
  widgetData:
    title: Tab list
    items:
      - resourceRefId: my-tab-list
  resourcesRefs:
    - id: my-tab-list
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: my-tab-list
      namespace: krateo-system
      resource: tablists
      verb: GET
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: panel-line-chart
  namespace: krateo-system
spec:
  widgetData:
    title: Line chart
    items:
      - resourceRefId: my-line-chart
  resourcesRefs:
    - id: my-line-chart
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: my-line-chart
      namespace: krateo-system
      resource: linecharts
      verb: GET
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: panel-bar-chart
  namespace: krateo-system
spec:
  widgetData:
    title: Bar chart
    items:
      - resourceRefId: my-bar-chart
  resourcesRefs:
    - id: my-bar-chart
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: my-bar-chart
      namespace: krateo-system
      resource: barcharts
      verb: GET
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: composition-test-panel
  namespace: krateo-system
spec:
  widgetData:
    footer:
      items:
        - resourceRefId: composition-test-button
      tag: krateo-system
    icon:
      name: fa-solid fa-cubes
      color: blue
    items:
      - resourceRefId: composition-test-paragraph
    title: composition-test
  resourcesRefs:
    - id: composition-test-paragraph
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-test-paragraph
      namespace: krateo-system
      resource: paragraphs
      verb: GET
    - id: composition-test-button
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-test-button
      namespace: krateo-system
      resource: buttons
      verb: GET