---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: my-panel
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: 2025-06-12T15:20:41+00:00
    items:
      - resourceRefId: my-pie-chart
      - resourceRefId: my-table
    tooltip: this is a tooltip!
    footer:
      - resourceRefId: button-1
      - resourceRefId: button-1
  resourcesRefs:
    - id: my-table
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: my-table
      namespace: krateo-system
      resource: tables
      verb: GET
    - id: my-pie-chart
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: my-pie-chart
      namespace: krateo-system
      resource: piecharts
      verb: GET
    - id: button-1
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: button-1
      namespace: krateo-system
      resource: buttons
      verb: GET
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: panel-with-row
  namespace: krateo-system
spec:
  widgetData:
    clickActionId: composition-click-action
    actions:
      navigate:
        - id: composition-click-action
          resourceRefId: my-tab-list
          type: navigate        
    title: Panel with Row
    items:
      - resourceRefId: first-row
  resourcesRefs:
    - id: first-row
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: first-row
      namespace: krateo-system
      resource: rows
      verb: GET
    - id: my-tab-list
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: my-tab-list
      namespace: krateo-system
      resource: tablists
      verb: GET
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: panel-with-column
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: Panel with Column
    headerLeft: 2025-06-11T15:20:41+00:00
    headerRight: small description
    items:
      - resourceRefId: first-column
    footer:
      - resourceRefId: button-with-drawer-filters
    tags:
      - tag1
      - tag2
  resourcesRefs:
    - id: first-column
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: first-column
      namespace: krateo-system
      resource: columns
      verb: GET
    - id: button-with-drawer-filters
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: button-with-drawer-filters
      namespace: krateo-system
      resource: buttons
      verb: GET
    - id: button-1
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: button-1
      namespace: krateo-system
      resource: buttons
      verb: GET
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: panel-paragraph
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: 2025-06-10T15:20:41+00:00 # Paragraph
    items:
      - resourceRefId: my-paragraph
  resourcesRefs:
    - id: my-paragraph
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: my-paragraph
      namespace: krateo-system
      resource: paragraphs
      verb: GET
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: panel-yaml-viewer
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: Yaml Viewer
    items:
      - resourceRefId: my-yaml-viewer
  resourcesRefs:
    - id: my-yaml-viewer
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: my-yaml-viewer
      namespace: krateo-system
      resource: yamlviewers
      verb: GET
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: panel-event-list
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: Event list
    items:
      - resourceRefId: my-event-list
  resourcesRefs:
    - id: my-event-list
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: my-event-list
      namespace: krateo-system
      resource: eventlists
      verb: GET
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: panel-tab-list
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: Tab list
    items:
      - resourceRefId: my-tab-list
  resourcesRefs:
    - id: my-tab-list
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: my-tab-list
      namespace: krateo-system
      resource: tablists
      verb: GET
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: panel-line-chart
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: Line chart
    items:
      - resourceRefId: my-line-chart
  resourcesRefs:
    - id: my-line-chart
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: my-line-chart
      namespace: krateo-system
      resource: linecharts
      verb: GET
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: panel-bar-chart
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: Bar chart
    items:
      - resourceRefId: my-bar-chart
  resourcesRefs:
    - id: my-bar-chart
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: my-bar-chart
      namespace: krateo-system
      resource: barcharts
      verb: GET
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: composition-test-panel
  namespace: krateo-system
spec:
  widgetData:
    clickActionId: composition-click-action
    footer:
      - resourceRefId: composition-test-button
    tags: 
      - krateo-system
    icon:
      name: fa-solid fa-cubes
      color: blue
    items:
      - resourceRefId: composition-test-paragraph
    title: composition-test
    actions:
      navigate:
        - id: composition-click-action
          resourceRefId: my-tab-list
          type: navigate
  resourcesRefs:
    - id: composition-test-paragraph
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-test-paragraph
      namespace: krateo-system
      resource: paragraphs
      verb: GET
    - id: composition-test-button
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-test-button
      namespace: krateo-system
      resource: buttons
      verb: GET
    - id: my-tab-list
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: my-tab-list
      namespace: krateo-system
      resource: tablists
      verb: GET
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: panel-filters
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: Composition Filters
    items:
      - resourceRefId: my-filters
  resourcesRefs:
    - id: my-filters
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: my-filters
      namespace: krateo-system
      resource: filters
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: panel-table-filters
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: Table Filters
    items:
      - resourceRefId: table-of-pods
  resourcesRefs:
    - id: table-of-pods
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: table-of-pods
      namespace: krateo-system
      resource: filters
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: fireworksapp-template-panel-schema-notordered
  namespace: krateo-system
  labels:
    krateo.io/portal-page: templates
spec:
  widgetData:
    clickActionId: template-click-action
    headerLeft: Ready:Unknown
    footer:
      - resourceRefId: composition-test-button
    tags:
      - krateo-system
      - 2.0.1
    icon:
      name: fa-solid fa-cubes
      color: blue
    items:
      - resourceRefId: my-paragraph
    title: FireworksApp (Not Ordered Schema)
    actions:
      openDrawer:
        - id: template-click-action
          resourceRefId: test-firework-form
          type: openDrawer
          size: large
          title: Fireworksapp
  resourcesRefs:
    - id: my-paragraph
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: my-paragraph
      namespace: krateo-system
      resource: paragraphs
      verb: GET
    - id: composition-test-button
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-test-button
      namespace: krateo-system
      resource: buttons
      verb: GET
    - id: test-firework-form
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: test-firework-form
      namespace: krateo-system
      resource: forms
      verb: GET
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: fireworksapp-template-panel-schema-notordered-2
  namespace: krateo-system
  labels:
    krateo.io/portal-page: templates
spec:
  widgetData:
    clickActionId: template-click-action
    headerLeft: Ready:Unknown
    footer:
      - resourceRefId: composition-test-button
    tags:
      - krateo-system
      - other-tag
    icon:
      name: fa-solid fa-cubes
      color: blue
    items:
      - resourceRefId: my-paragraph
    title: Different title and tags!
    actions:
      openDrawer:
        - id: template-click-action
          resourceRefId: test-firework-form
          type: openDrawer
          size: large
          title: Fireworksapp
  resourcesRefs:
    - id: my-paragraph
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: my-paragraph
      namespace: krateo-system
      resource: paragraphs
      verb: GET
    - id: composition-test-button
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-test-button
      namespace: krateo-system
      resource: buttons
      verb: GET
    - id: test-firework-form
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: test-firework-form
      namespace: krateo-system
      resource: forms
      verb: GET