kind: Button
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: button-delete-test-app
  namespace: test-namespace
spec:
  widgetData:
    icon: fa-trash
    type: default
    shape: circle
    clickActionId: delete
    actions:
      rest:
        - id: delete
          resourceRefId: delete
          type: rest
          requireConfirmation: true
  resourcesRefs:
    items:
      - id: delete
        apiVersion: composition.krateo.io/v1-1-15
        resource: testapps
        name: hello-test-2
        namespace: test-namespace
        verb: DELETE