kind: Button
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: button-1
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    label: button 1
    icon: fa-sun
    type: primary
    clickActionId: action-1
  resourcesRefs: {
    items: []
  }
---
kind: Button
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: composition-test-button
  namespace: krateo-system
spec:
  widgetData:
    actions: 
      rest:
      - id: cleanup
        errorMessage: Error!
        successMessage: Success!
        resourceRefId: cleanup
        type: rest
        onSuccessNavigateTo: /templates
    icon: fa-trash
    type: default
    shape: circle
    clickActionId: cleanup
  resourcesRefs:
    items:
      - id: cleanup
        apiVersion: templates.krateo.io/v1
        resource: restactions
        name: fireworksapp-template-restaction-cleanup
        namespace: krateo-system
        verb: GET
