kind: Button
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: button-1
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    label: button 1
    icon: fa-sun
    type: primary
    clickActionId: action-1
  resourcesRefs: []
---
kind: Button
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: composition-test-button
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    icon: fa-trash
    type: default
    shape: circle
    clickActionId: action-1
  resourcesRefs: []
