---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: httpbin-endpoint
  namespace: krateo-system
stringData:
  server-url: https://httpbin.org
---
apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: httpbin-simple
  namespace: krateo-system
spec:
  api:
  - name: one
    path: "/get?label=Hello+World&icon=fa-earth-europe"
    endpointRef:
      name: httpbin-endpoint
      namespace: krateo-system

---
apiVersion: widgets.templates.krateo.io/v1beta1
kind: Button
metadata:
  namespace: krateo-system
  name: button-with-api
spec:
  widgetData:
    label: label
    icon: fa-clock
    type: text
  widgetDataTemplate:
    - forPath: label
      expression: ${ .one.args.label }
    - forPath: icon
      expression: ${ .one.args.icon }
  apiRef:
    name: httpbin-simple
    namespace: krateo-system