kind: Button
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: button-with-drawer-form
  namespace: krateo-system
spec:
  widgetData:
    label: Open Form (in Drawer)
    icon: fa-rocket
    size: large
    type: primary
    clickActionId: open-drawer-action
    actions:
      openDrawer:
        - id: open-drawer-action
          resourceRefId: test-firework-form
          type: openDrawer
          title: Form in Drawer
          size: large
  resourcesRefs:
    - id: test-firework-form
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: test-firework-form
      namespace: krateo-system
      resource: forms
      verb: GET
---
kind: Button
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: button-with-modal-form
  namespace: krateo-system
spec:
  widgetData:
    label: Open Form (in Modal)
    icon: fa-rocket
    size: large
    type: primary
    clickActionId: open-modal-action
  actions:
    openModal:
      - id: open-modal-action
        name: open-modal-action
        resourceRefId: firework-form
        type: openModal
        title: Form in Modal
  resourcesRefs:
    - id: firework-form
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: firework-form
      namespace: krateo-system
      resource: forms
      verb: GET