kind: Button
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: button-test-action-get
  namespace: krateo-system
spec:
  widgetData:
    allowedResources:
      - barcharts
        buttons
        columns
        datagrids
        eventlists
        filters
        flowcharts
        forms
        linecharts
        markdowns
        pages
        panels
        paragraphs
        piecharts
        restactions
        rows
        tables
        tablists
        yamlviewers
    label: Test GET
    icon: fa-rocket
    type: primary
    clickActionId: get-default-pod
    actions:
      rest:
        - id: get-default-pod
          resourceRefId: get-pod-default
          type: rest
          loading:
            display: true
          successMessage: "Pod letto correttamente"
          errorMessage: "Errore nella lettura del pod"
  resourcesRefs:
    items: []