kind: Button
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: button-with-drawer-form
  namespace: krateo-system
spec:
  widgetData:
    label: Open Form
    icon: fa-rocket
    size: large
    type: primary
    clickActionId: my-click-action
  actions:
    openModal:
      - id: my-click-action
        name: modal
        resourceRefId: firework-form
        type: openModal
  resourcesRefs:
    - id: firework-form
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: firework-form
      namespace: krateo-system
      resource: forms
      verb: GET