kind: Button
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: button-test-action-get
  namespace: krateo-system
spec:
  widgetData:
    label: Test GET
    icon: fa-rocket
    type: primary
    clickActionId: get-default-pod
    actions:
      rest:
        - id: get-default-pod
          resourceRefId: get-pod-default
          type: rest
          loading:
            display: true
          successMessage: "Pod letto correttamente"
          errorMessage: "Errore nella lettura del pod"
  resourcesRefs:
    - id: get-pod-default
      apiVersion: v1
      resource: pods
      verb: GET
      name: cratedb-0
      namespace: krateo-system