kind: Button
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: button-with-drawer-filters
  namespace: krateo-system
spec:
  widgetData:
    allowedResources:
    - barcharts
    - buttons
    - columns
    - datagrids
    - eventlists
    - filters
    - flowcharts
    - forms
    - linecharts
    - markdowns
    - pages
    - panels
    - paragraphs
    - piecharts
    - restactions
    - rows
    - tables
    - tablists
    - yamlviewers
    label: Filters
    icon: fa-rocket
    size: middle
    type: default
    clickActionId: my-click-action
    actions:
      openDrawer:
        - id: my-click-action
          resourceRefId: my-filters
          type: openDrawer
          title: Filter compositions
          size: large
  resourcesRefs:
    items:
      - id: my-filters
        apiVersion: widgets.templates.krateo.io/v1beta1
        resource: filters
        name: my-filters
        namespace: krateo-system
        verb: GET
---
kind: Button
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: button-with-drawer-filters-2
  namespace: krateo-system
spec:
  widgetData:
    allowedResources:
    - barcharts
    - buttons
    - columns
    - datagrids
    - eventlists
    - filters
    - flowcharts
    - forms
    - linecharts
    - markdowns
    - pages
    - panels
    - paragraphs
    - piecharts
    - restactions
    - rows
    - tables
    - tablists
    - yamlviewers
    label: Filters
    icon: fa-filter
    size: middle
    type: default
    clickActionId: my-click-action
    actions:
      openDrawer:
        - id: my-click-action
          resourceRefId: panel-filters
          type: openDrawer
          title: Filter compositions
          size: large
  resourcesRefs:
    items:
      - id: panel-filters
        apiVersion: widgets.templates.krateo.io/v1beta1
        resource: filters
        name: panel-filters
        namespace: krateo-system
        verb: GET


