kind: Button
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: test-navigate-page
  namespace: krateo-system
spec:
  widgetData:
    actions:
      navigate:
        - id: navigate-action-page
          path: /templates
          type: navigate    
    label: Navigate to templates
    icon: fa-sun
    type: primary
    clickActionId: navigate-action-page
  resourcesRefs:
    items:
      - id: templates-page
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: templates-page
        namespace: krateo-system
        resource: pages
        verb: GET
---
kind: Button
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: test-navigate-page-2
  namespace: krateo-system
spec:
  widgetData:
    actions:
      navigate:
        - id: navigate-action-page
          path: /compositions
          type: navigate    
    label: Navigate to composition
    icon: fa-sun
    type: primary
    clickActionId: navigate-action-page
  resourcesRefs:
    items:
      - id: compositions-page
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: compositions-page
        namespace: krateo-system
        resource: pages
        verb: GET
---
kind: Button
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: button-1
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    label: button 1
    icon: fa-sun
    type: primary
    clickActionId: action-1
  resourcesRefs: {
    items: []
  }
---
kind: Button
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: composition-test-button
  namespace: krateo-system
spec:
  widgetData:
    actions: 
      rest:
      - id: cleanup
        errorMessage: Error!
        successMessage: Success!
        resourceRefId: cleanup
        type: rest
        onSuccessNavigateTo: /templates
    icon: fa-trash
    type: default
    shape: circle
    clickActionId: cleanup
  resourcesRefs:
    items:
      - id: cleanup
        apiVersion: templates.krateo.io/v1
        resource: restactions
        name: fireworksapp-template-restaction-cleanup
        namespace: krateo-system
        verb: GET
