kind: Button
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: button-delete-fireworks-app
  namespace: krateo-system
spec:
  widgetData:
    icon: fa-trash
    type: default
    shape: circle
    clickActionId: delete
  actions:
    rest:
      - id: delete
        resourceRefId: delete
        type: rest
        requireConfirmation: true
  resourcesRefs:
    - id: delete
      apiVersion: composition.krateo.io/v1-1-15
      resource: fireworksapps
      name: hello-test-2
      namespace: fireworksapp-system
      verb: DELETE