kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: nginx-form-panel
  namespace: krateo-system
spec:
  widgetData:
    title: Nginx factory
    items:
      - resourceRefId: nginx-form
  resourcesRefs:
    - id: nginx-form
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: nginx-form
      namespace: krateo-system
      resource: forms
      verb: GET
---
kind: Form
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: nginx-form
  namespace: krateo-system
spec:
  widgetData:
    schema: {}
  actions:
    rest: []

  widgetDataTemplate:
    - forPath: schema
      expression: ${ .getNginxSchema | .spec.versions[] | select(.name == "v0-1-0") | .schema.openAPIV3Schema.properties.spec }
  apiRef:
    name: nginx-schema
    namespace: krateo-system
---
apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: nginx-schema
  namespace: krateo-system
spec:
  api:
  - name: getNginxSchema
    verb: GET
    path: "/apis/apiextensions.k8s.io/v1/customresourcedefinitions/nginxes.composition.krateo.io"
    headers:
    - 'Accept: application/json'