kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: firework-form-panel
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: Firework App Form
    items:
      - resourceRefId: firework-form
  resourcesRefs:
    - id: firework-form
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: firework-form
      namespace: krateo-system
      resource: forms
      verb: GET
---
kind: Form
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: firework-form
  namespace: krateo-system
spec:
  widgetData:
    schema: {}
    submitActionId: firework-submit-action
    actions:
      rest:
        - id: firework-submit-action
          resourceRefId: resource-ref-1
          type: rest
          onSuccessNavigateTo: /compositions/${metadata.namespace}/${metadata.name}
          payloadToOverride:
          - name: metadata.name
            value: ${ git.toRepo.name }
  widgetDataTemplate:
    - forPath: schema
      expression: ${ .getSchema | .spec.versions[] | select(.name == "v2-0-0") | .schema.openAPIV3Schema.properties.spec }
  resourcesRefs:
    - id: resource-ref-1
      apiVersion: composition.krateo.io/v2-0-0
      name: new-app
      namespace: fireworksapp-system
      resource: fireworksapps
      verb: POST
  apiRef:
    name: firework-schema
    namespace: krateo-system
---
apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: firework-schema
  namespace: krateo-system
spec:
  api:
  - name: getSchema
    verb: GET
    path: "/apis/apiextensions.k8s.io/v1/customresourcedefinitions/fireworksapps.composition.krateo.io"
    headers:
    - 'Accept: application/json'
---
kind: Form
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: test-firework-form
  namespace: krateo-system
spec:
  widgetData:
    submitActionId: firework-submit-action
    stringSchema: |
      {
        "type": "object",
        "properties": {
          "loremipsum2": {
            "type": "string",
            "title": "Lorem ipsum2",
            "description": "bla bla bla"
          },
          "loremipsum3": {
            "type": "string",
            "title": "Lorem ipsum3",
            "description": "bla bla bla"
          },
          "name": {
            "type": "string",
            "title": "Application Name",
            "description": "The name of your fireworks app"
          },
          "loremipsum": {
            "type": "string",
            "title": "Lorem ipsum",
            "description": "bla bla bla"
          },
          "image": {
            "type": "string",
            "title": "Container Image",
            "description": "Full image path (e.g., ghcr.io/org/image:tag)"
          },
          "replicas": {
            "type": "integer",
            "title": "Number of Replicas",
            "default": 1
          },
          "select1": {
            "type": "string",
            "title": "regione",
            "description": "The list of regions",
            "enum": [
              "Piemonte",
              "Lombardia",
              "Veneto",
              "Emilia-Romagna",
              "Toscana",
              "Liguria"
            ]
          },
          "select2": {
            "type": "string",
            "title": "province",
            "description": "The list of provinces",
            "enum": []
          },
          "enableMetrics": {
            "type": "boolean",
            "title": "Enable Metrics",
            "default": false
          }
        },
        "required": ["name", "image", "enableMetrics"]
      }
    autocomplete:
      - path: name
        fetch:
          url: https://loremipsum.io/api/1
          verb: GET
    dependencies:
      - path: select2
        dependsField: 
          field: select1
          when: changed
        fetch:
          url: https://loremipsum.io/api/provinces/
          verb: GET
    actions:
      rest:
        - id: firework-submit-action
          resourceRefId: resource-ref-1
          type: rest
          payloadKey: spec
          onSuccessNavigateTo: /compositions/${metadata.namespace}/${metadata.name}
          payloadToOverride:
            - name: metadata.name
              value: ${ git.toRepo.name }
  resourcesRefs:
    - id: resource-ref-1
      apiVersion: composition.krateo.io/v2-0-0
      name: new-app
      namespace: fireworksapp-system
      resource: fireworksapps
      verb: POST
