kind: NavMenuItem
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: nav-menu-item-templates
  namespace: test-namespace
spec:
  widgetData:
    allowedResources:
      - pages
    resourceRefId: templates-page
    label: Templates
    icon: fa-rectangle-list
    path: /templates
    order: 20

  resourcesRefs:
    items:
      - id: templates-page
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: templates-page
        namespace: test-namespace
        resource: pages
        verb: GET