# Empty items array
# Target: TabList definition with no items provided.
# Expected behavior: The widget renders no tabs and no content. This is an intentional empty state.
# It should not throw validation errors, as `items` can be empty.
kind: TabList
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-tablist-empty-items
  namespace: krateo-system
spec:
  widgetData:
    allowedResources:
      - markdowns
      - paragraphs
    items: []
  resourcesRefs:
    items: []
---
# Invalid resource reference
# Target: references a non-existing resourceRefId.
# Expected behavior: The tab label is still rendered, but an error is displayed,
# to inform that the referenced resource cannot be resolved from `resourcesRefs`.
kind: TabList
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-tablist-invalid-resource
  namespace: krateo-system
spec:
  widgetData:
    allowedResources:
      - markdowns
      - paragraphs
    items:
      - label: Orphan Tab
        resourceRefId: missing-ref
  resourcesRefs:
    items: []
---
# Basic tab list with single valid tab
# Target: one correctly resolved tab referencing a markdown resource.
# Expected behavior: the widget displays a single tab with its label and the resolved child content.
kind: TabList
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-tablist-single-tab
  namespace: krateo-system
spec:
  widgetData:
    allowedResources:
      - markdowns
    items:
      - label: Overview
        resourceRefId: example-markdown-basic
  resourcesRefs:
    items:
      - id: example-markdown-basic
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-markdown-basic
        namespace: krateo-system
        resource: markdowns
        verb: GET
---
# Multiple tabs with mixed content types
# Target: demonstrates rendering multiple tabs where each tab references a different type of resource.
# Expected behavior: each tab loads its corresponding widget; switching between tabs should change the visible content.
kind: TabList
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-tablist-mixed-resources
  namespace: krateo-system
spec:
  widgetData:
    allowedResources:
      - markdowns
      - piecharts
      - linecharts
    items:
      - label: Description
        title: About this system
        resourceRefId: example-markdown-basic
      - label: Usage Metrics
        resourceRefId: example-linechart-multi
      - label: Distribution
        title: Resource allocation by type
        resourceRefId: example-piechart-full-fill
  resourcesRefs:
    items:
      - id: example-markdown-basic
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-markdown-basic
        namespace: krateo-system
        resource: markdowns
        verb: GET
      - id: example-linechart-multi
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-linechart-multi
        namespace: krateo-system
        resource: linecharts
        verb: GET
      - id: example-piechart-full-fill
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-piechart-full-fill
        namespace: krateo-system
        resource: piecharts
        verb: GET
---
# Tab list with titles for all tabs
# Target: uses the `title` field for each item to provide contextual headers inside each tab.
# Expected behavior: each tab displays its title above the tab content.
kind: TabList
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-tablist-titled-tabs
  namespace: krateo-system
spec:
  widgetData:
    allowedResources:
      - markdowns
      - piecharts
    items:
      - label: Details
        title: System Details
        resourceRefId: example-markdown-basic
      - label: Chart
        title: Resource Chart
        resourceRefId: example-piechart-full-fill
  resourcesRefs:
    items:
      - id: example-markdown-basic
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-markdown-basic
        namespace: krateo-system
        resource: markdowns
        verb: GET
      - id: example-piechart-full-fill
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-piechart-full-fill
        namespace: krateo-system
        resource: piecharts
        verb: GET