kind: NavMenuItem
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: simple-guide-nav-menu-item
  namespace: krateo-system
spec:
  widgetData:
    allowedResources: [pages]
    resourceRefId: page-id
    label: Simple guide
    icon: fa-sun
    path: /simple-guide
  resourcesRefs:
    items:
      - id: page-id
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: simple-guide-page
        namespace: krateo-system
        resource: pages
        verb: GET