apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: compositions-panels
  namespace: krateo-system
spec:
  api:
  - filter: '[.namespaces.items[] | .metadata.name]'
    name: namespaces
    path: /api/v1/namespaces
  - continueOnError: true
    dependsOn:
      iterator: .namespaces
      name: namespaces
    name: compositionspanels
    path: ${ "/apis/widgets.templates.krateo.io/v1beta1/namespaces/" + (.) + "/panels"
      }
  filter: |
    {
      compositionspanels: (
        (if (.compositionspanels | type) == "array" then
          [.compositionspanels[]?.items[]? | select((.metadata.labels // {})["krateo.io/portal-page"] == "compositions")]
        elif (.compositionspanels | type) == "object" then
          [.compositionspanels.items[]?    | select((.metadata.labels // {})["krateo.io/portal-page"] == "compositions")]
        else
          []
        end)
      )
    }
