---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: httpbin-endpoint
  namespace: krateo-system
stringData:
  server-url: https://httpbin.org
---
apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: httpbin-simple
  namespace: krateo-system
spec:
  api:
  - name: one
    path: "/get?label=Hello+World&icon=fa-earth-europe"
    endpointRef:
      name: httpbin-endpoint
      namespace: krateo-system