kind: BarChart
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: my-bar-chart
  namespace: test-namespace
spec:
  widgetData:
    data:
      - label: CPU usage
        bars:
          - value: "1982"
            percentage: 75
            color: blue
          - value: "75"
            percentage: 12
            color: red
      - label: RAM usage
        bars:
          - value: "72"
            percentage: 12
            color: orange
      - label: Temperature
        bars:
          - value: "63"
            percentage: 85
            color: red