
kind: CompositionCard
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: composition-test-card
  namespace: test-namespace
spec:
  widgetData:
    date: 2023-08-20'T'13:20:10*633+0000
    status: Ready
    tooltip: test
    navigateToDetailActionId: composition-click-action
    deleteCompositionActionId: composition-delete-action
    tags: 
      - test-namespace
      - test-system
    icon:
      name: fa-solid fa-cubes
      color: blue
    title: composition-test
    description: This is a test composition card.
    actions:
      navigate:
        - id: composition-click-action
          name: composition-click-action
          resourceRefId: composition-test-tab-list
          type: navigate
      rest:
        - id: composition-delete-action
          resourceRefId: composition-test-panel
          type: rest
  resourcesRefs:
    - id: composition-test-panel
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-test-panel
      namespace: test-namespace
      resource: panels
      verb: GET
    - id: composition-test-tab-list
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-test-tab-list
      namespace: test-namespace
      resource: tablists
      verb: GET