
kind: CompositionCard
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: composition-test-card
  namespace: krateo-system
spec:
  widgetData:
    date: ""
    status: ""
    tooltip: test
    navigateToDetailActionId: composition-click-action
    deleteCompositionActionId: composition-delete-action
    tags: 
      - krateo-system
      - test-system
    icon:
      name: fa-solid fa-cubes
      color: blue
    title: composition-test
    description: This is a test composition card.
    actions:
      navigate:
        - id: composition-click-action
          name: composition-click-action
          resourceRefId: composition-test-tab-list
          type: navigate
      rest:
        - id: composition-delete-action
          resourceRefId: composition-test-panel
          type: rest
  resourcesRefs:
    - id: composition-test-paragraph
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-test-paragraph
      namespace: krateo-system
      resource: paragraphs
      verb: GET
    - id: composition-test-button
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-test-button
      namespace: krateo-system
      resource: buttons
      verb: GET
    - id: composition-test-tab-list
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-test-tab-list
      namespace: krateo-system
      resource: tablists
      verb: GET
  widgetDataTemplate:
    - forPath: title
      expression: ${ .getCompositionDefinition.metadata.name }
    - forPath: date
      expression: ${ .getCompositionDefinition.metadata.namespace }
    - forPath: status
      expression: ${ .getCompositionDefinition.status.conditions[] | select(.type == "Ready") | "Ready:" + " " + .status }
  apiRef:
    name: compositionsrestaction
    namespace: krateo-system

---
apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: compositionsrestaction
  namespace: krateo-system
spec:
  api:
  - name: getCompositionDefinition
    path: "/apis/core.krateo.io/v1alpha1/namespaces/fireworksapp-system/compositiondefinitions/fireworksapp"

---
kind: TabList
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: composition-test-tab-list
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    items:
      - label: Overview
        resourceRefId: composition-test-panel-paragraph
      - label: Composition Status
        resourceRefId: my-flow-chart
      - label: Application Status
        resourceRefId: my-flow-chart
      - label: Events
        resourceRefId: composition-test-panel-event-list
      - label: Values
        resourceRefId: composition-test-panel-yaml-viewer
  resourcesRefs:
    - id: composition-test-panel-paragraph
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-test-panel-paragraph
      namespace: krateo-system
      resource: panels
      verb: GET
    - id: my-flow-chart
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: my-flow-chart
      namespace: krateo-system
      resource: flowcharts
      verb: GET
    - id: my-flow-chart
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: my-flow-chart
      namespace: krateo-system
      resource: flowcharts
      verb: GET
    - id: composition-test-panel-event-list
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-test-panel-event-list
      namespace: krateo-system
      resource: panels
      verb: GET
    - id: composition-test-panel-yaml-viewer
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-test-panel-yaml-viewer
      namespace: krateo-system
      resource: panels
      verb: GET

---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: composition-test-panel-paragraph
  namespace: krateo-system
spec:
  actions: {}
  widgetData:
    items:
      - resourceRefId: my-paragraph
  resourcesRefs:
    - id: my-paragraph
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: my-paragraph
      namespace: krateo-system
      resource: paragraphs
      verb: GET

---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: composition-test-panel-event-list
  namespace: krateo-system
spec:
  actions: {}
  widgetData:
    items:
      - resourceRefId: my-event-list
  resourcesRefs:
    - id: my-event-list
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: my-event-list
      namespace: krateo-system
      resource: eventlists
      verb: GET


---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: composition-test-panel-yaml-viewer
  namespace: krateo-system
spec: 
  actions: {}
  widgetData:
    items:
      - resourceRefId: my-yaml-viewer
  resourcesRefs:
    - id: my-yaml-viewer
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: my-yaml-viewer
      namespace: krateo-system
      resource: yamlviewers
      verb: GET

---
kind: CompositionCard
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: composition-filtrable-card-1
  namespace: krateo-system
spec:
  widgetData:
    date: 2025-06-11T15:20:41+00:00
    status: pending
    tooltip: test
    navigateToDetailActionId: composition-click-action
    deleteCompositionActionId: composition-delete-action
    tags: 
      - krateo-system
      - test-system
    icon:
      name: fa-solid fa-cubes
      color: blue
    title: comp 1
    description: This is a test composition card. With a long description to make sure it overflow and the Row is bigger than expected.
    actions:
      navigate:
        - id: composition-click-action
          name: composition-click-action
          resourceRefId: composition-test-tab-list
          type: navigate
      rest:
        - id: composition-delete-action
          resourceRefId: composition-test-panel
          type: rest
  resourcesRefs:
    - id: composition-test-paragraph
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-test-paragraph
      namespace: krateo-system
      resource: paragraphs
      verb: GET
    - id: composition-test-button
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-test-button
      namespace: krateo-system
      resource: buttons
      verb: GET
    - id: composition-test-tab-list
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-test-tab-list
      namespace: krateo-system
      resource: tablists
      verb: GET

---
kind: CompositionCard
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: composition-filtrable-card-2
  namespace: krateo-system
spec:
  widgetData:
    date: 2025-06-12T15:20:41+00:00
    status: active
    tooltip: test
    navigateToDetailActionId: composition-click-action
    deleteCompositionActionId: composition-delete-action
    tags: 
      - krateo-system
      - test-system
      - lorem-ipsum
    icon:
      name: fa-solid fa-cubes
      color: green
    title: comp 2
    description: This is a test composition card.
    actions:
      navigate:
        - id: composition-click-action
          name: composition-click-action
          resourceRefId: composition-test-tab-list
          type: navigate
      rest:
        - id: composition-delete-action
          resourceRefId: composition-test-panel
          type: rest
  resourcesRefs:
    - id: composition-test-paragraph
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-test-paragraph
      namespace: krateo-system
      resource: paragraphs
      verb: GET
    - id: composition-test-button
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-test-button
      namespace: krateo-system
      resource: buttons
      verb: GET
    - id: composition-test-tab-list
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-test-tab-list
      namespace: krateo-system
      resource: tablists
      verb: GET


---
kind: CompositionCard
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: composition-filtrable-card-3
  namespace: krateo-system
spec:
  widgetData:
    date: 2025-06-13T15:20:41+00:00
    status: disabled
    tooltip: test
    navigateToDetailActionId: composition-click-action
    deleteCompositionActionId: composition-delete-action
    tags: 
      - krateo-system
      - test-system
      - dolor-sit-amet
    icon:
      name: fa-solid fa-cubes
      color: red
    title: comp 3
    description: This is a test composition card.
    actions:
      navigate:
        - id: composition-click-action
          name: composition-click-action
          resourceRefId: composition-test-tab-list
          type: navigate
      rest:
        - id: composition-delete-action
          resourceRefId: composition-test-panel
          type: rest
  resourcesRefs:
    - id: composition-test-paragraph
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-test-paragraph
      namespace: krateo-system
      resource: paragraphs
      verb: GET
    - id: composition-test-button
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-test-button
      namespace: krateo-system
      resource: buttons
      verb: GET
    - id: composition-test-tab-list
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-test-tab-list
      namespace: krateo-system
      resource: tablists
      verb: GET
---
kind: CompositionCard
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: composition-filtrable-card-4
  namespace: krateo-system
spec:
  widgetData:
    date: 2025-06-12T15:20:41+00:00
    status: active
    tooltip: test
    navigateToDetailActionId: composition-click-action
    deleteCompositionActionId: composition-delete-action
    tags: 
      - krateo-system
      - test-system
      - consectetur-adipiscing
    icon:
      name: fa-solid fa-cubes
      color: green
    title: comp 4
    description: This is a test composition card.
    actions:
      navigate:
        - id: composition-click-action
          name: composition-click-action
          resourceRefId: composition-test-tab-list
          type: navigate
      rest:
        - id: composition-delete-action
          resourceRefId: composition-test-panel
          type: rest
  resourcesRefs:
    - id: composition-test-paragraph
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-test-paragraph
      namespace: krateo-system
      resource: paragraphs
      verb: GET
    - id: composition-test-button
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-test-button
      namespace: krateo-system
      resource: buttons
      verb: GET
    - id: composition-test-tab-list
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-test-tab-list
      namespace: krateo-system
      resource: tablists
      verb: GET


---
kind: CompositionCard
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: composition-filtrable-card-5
  namespace: krateo-system
spec:
  widgetData:
    date: 2025-06-13T15:20:41+00:00
    status: disabled
    tooltip: test
    navigateToDetailActionId: composition-click-action
    deleteCompositionActionId: composition-delete-action
    tags: 
      - krateo-system
      - test-system
      - morbi-dictum-est
    icon:
      name: fa-solid fa-cubes
      color: red
    title: comp 5
    description: This is a test composition card.
    actions:
      navigate:
        - id: composition-click-action
          name: composition-click-action
          resourceRefId: composition-test-tab-list
          type: navigate
      rest:
        - id: composition-delete-action
          resourceRefId: composition-test-panel
          type: rest
  resourcesRefs:
    - id: composition-test-paragraph
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-test-paragraph
      namespace: krateo-system
      resource: paragraphs
      verb: GET
    - id: composition-test-button
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-test-button
      namespace: krateo-system
      resource: buttons
      verb: GET
    - id: composition-test-tab-list
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-test-tab-list
      namespace: krateo-system
      resource: tablists
      verb: GET