kind: LineChart
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: my-line-chart
  namespace: krateo-system
spec:
  widgetData:
    lines:
      - name: linea blu
        color: blue
        coords:
          - xAxis: 0
            yAxis: 15
          - xAxis: 1
            yAxis: 52
          - xAxis: 2
            yAxis: 15
          - xAxis: 3
            yAxis: 52
      - name: linea rossa
        color: red
        coords:
          - xAxis: 0
            yAxis: 4
          - xAxis: 1
            yAxis: 8
          - xAxis: 2
            yAxis: 12
          - xAxis: 3
            yAxis: 2
    xAxisName: tempo
    yAxisName: costo
---

kind: LineChart
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: line-chart-with-dates
  namespace: krateo-system
spec:
  widgetData:
    prefix: filters-pods
    lines:
      - name: blue line
        color: blue
        coords:
          - xAxis: 2025-06-01T00:00:00+00:00
            yAxis: 15
          - xAxis: 2025-07-02T00:00:00+00:00
            yAxis: 52
          - xAxis: 2025-06-03T00:00:00+00:00
            yAxis: 24
          - xAxis: 2025-06-04T00:00:00+00:00
            yAxis: 4
    xAxisName: time
    yAxisName: cost

---
kind: LineChart
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: line-chart-with-dates-2
  namespace: krateo-system
spec:
  widgetData:
    prefix: filters-pods
    lines:
      - name: blue line
        color: blue
        coords:
          - xAxis: 2025-06-03T00:00:00+00:00
            yAxis: 31
          - xAxis: 2025-06-04T00:00:00+00:00
            yAxis: 49
          - xAxis: 2025-06-05T00:00:00+00:00
            yAxis: 18
          - xAxis: 2025-06-06T00:00:00+00:00
            yAxis: 9
          - xAxis: 2025-06-07T00:00:00+00:00
            yAxis: 27
          - xAxis: 2025-06-08T00:00:00+00:00
            yAxis: 36
    xAxisName: time
    yAxisName: cost