kind: LineChart
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: my-line-chart
  namespace: krateo-system
spec:
  widgetData:
    lines:
      - name: linea blu
        color: blue
        coords:
          - xAxis: 0
            yAxis: 15
          - xAxis: 1
            yAxis: 52
          - xAxis: 2
            yAxis: 15
          - xAxis: 3
            yAxis: 52
      - name: linea rossa
        color: red
        coords:
          - xAxis: 0
            yAxis: 4
          - xAxis: 1
            yAxis: 8
          - xAxis: 2
            yAxis: 12
          - xAxis: 3
            yAxis: 2
    xAxisName: tempo
    yAxisName: costo