kind: PieChart
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: my-pie-chart
  namespace: krateo-system
spec:
  widgetData:
    title: My Panel
    description: This is a description
    total: 100
    data:
      - color: blue
        value: 10
        label: Blue
      - color: darkBlue
        value: 20
        label: Dark Blue
      - color: orange
        value: 30
        label: Orange
        
