kind: NavMenuItem
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-flowchart-navmenuitem
  namespace: krateo-system
spec:
  widgetData:
    allowedResources:
      - pages
    resourceRefId: example-flowchart-page
    label: FlowChart
    icon: fa-chart-diagram
    path: /flowchart
  resourcesRefs:
    items:
      - id: example-flowchart-page
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-flowchart-page
        namespace: krateo-system
        resource: pages
        verb: GET
---
kind: Page
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-flowchart-page
  namespace: krateo-system
spec:
  widgetData:
    allowedResources:
      - barcharts
      - buttons
      - columns
      - datagrids
      - eventlists
      - filters
      - flowcharts
      - forms
      - linecharts
      - markdowns
      - panels
      - paragraphs
      - piecharts
      - rows
      - tables
      - tablists
      - yamlviewers
    items:
      - resourceRefId: example-flowchart-empty-panel
      - resourceRefId: example-flowchart-empty-nodes-panel
      - resourceRefId: example-flowchart-no-edges-panel
      - resourceRefId: example-flowchart-basic-panel
      - resourceRefId: example-flowchart-hierarchy-panel
      - resourceRefId: example-flowchart-cross-ns-panel
      - resourceRefId: example-flowchart-status-mix-panel
      - resourceRefId: example-flowchart-orphans-panel
      - resourceRefId: example-flowchart-multi-root-panel
  resourcesRefs:
    items:
      - id: example-flowchart-empty-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-flowchart-empty-panel
        namespace: krateo-system
        resource: panels
        verb: GET  
      - id: example-flowchart-empty-nodes-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-flowchart-empty-nodes-panel
        namespace: krateo-system
        resource: panels
        verb: GET  
      - id: example-flowchart-no-edges-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-flowchart-no-edges-panel
        namespace: krateo-system
        resource: panels
        verb: GET      
      - id: example-flowchart-basic-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-flowchart-basic-panel
        namespace: krateo-system
        resource: panels
        verb: GET       
      - id: example-flowchart-hierarchy-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-flowchart-hierarchy-panel
        namespace: krateo-system
        resource: panels
        verb: GET  
      - id: example-flowchart-cross-ns-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-flowchart-cross-ns-panel
        namespace: krateo-system
        resource: panels
        verb: GET
      - id: example-flowchart-status-mix-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-flowchart-status-mix-panel
        namespace: krateo-system
        resource: panels
        verb: GET
      - id: example-flowchart-orphans-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-flowchart-orphans-panel
        namespace: krateo-system
        resource: panels
        verb: GET
      - id: example-flowchart-multi-root-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-flowchart-multi-root-panel
        namespace: krateo-system
        resource: panels
        verb: GET
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-flowchart-empty-panel
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: 'Case 1: Empty nodes and edges'
    items:
      - resourceRefId: example-flowchart-empty
  resourcesRefs:
    items:
      - id: example-flowchart-empty
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-flowchart-empty
        namespace: krateo-system
        resource: flowcharts
        verb: GET  
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-flowchart-empty-nodes-panel
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: 'Case 2: Node with missing parent reference'
    items:
      - resourceRefId: example-flowchart-empty-nodes
  resourcesRefs:
    items:
      - id: example-flowchart-empty-nodes
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-flowchart-empty-nodes
        namespace: krateo-system
        resource: flowcharts
        verb: GET
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-flowchart-no-edges-panel
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: 'Case 3: Nodes without edges'
    items:
      - resourceRefId: example-flowchart-no-edges
  resourcesRefs:
    items:
      - id: example-flowchart-no-edges
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-flowchart-no-edges
        namespace: krateo-system
        resource: flowcharts
        verb: GET
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-flowchart-basic-panel
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: 'Case 4: Basic flow'
    items:
      - resourceRefId: example-flowchart-basic
  resourcesRefs:
    items:
      - id: example-flowchart-basic
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-flowchart-basic
        namespace: krateo-system
        resource: flowcharts
        verb: GET  
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-flowchart-hierarchy-panel
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: 'Case 5: Deep hierarchy'
    items:
      - resourceRefId: example-flowchart-hierarchy
  resourcesRefs:
    items:
      - id: example-flowchart-hierarchy
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-flowchart-hierarchy
        namespace: krateo-system
        resource: flowcharts
        verb: GET  
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-flowchart-cross-ns-panel
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: 'Case 6: Cross-namespace links'
    items:
      - resourceRefId: example-flowchart-cross-ns
  resourcesRefs:
    items:
      - id: example-flowchart-cross-ns
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-flowchart-cross-ns
        namespace: krateo-system
        resource: flowcharts
        verb: GET  
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-flowchart-status-mix-panel
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: 'Case 7: Mixed statuses'
    items:
      - resourceRefId: example-flowchart-status-mix
  resourcesRefs:
    items:
      - id: example-flowchart-status-mix
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-flowchart-status-mix
        namespace: krateo-system
        resource: flowcharts
        verb: GET  
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-flowchart-orphans-panel
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: 'Case 8: Missing parents'
    items:
      - resourceRefId: example-flowchart-orphans
  resourcesRefs:
    items:
      - id: example-flowchart-orphans
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-flowchart-orphans
        namespace: krateo-system
        resource: flowcharts
        verb: GET  
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-flowchart-multi-root-panel
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: 'Case 9: Multiple roots'
    items:
      - resourceRefId: example-flowchart-multi-root
  resourcesRefs:
    items:
      - id: example-flowchart-multi-root
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-flowchart-multi-root
        namespace: krateo-system
        resource: flowcharts
        verb: GET  