kind: Paragraph
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: my-paragraph
  namespace: krateo-system
spec:
  widgetData:
    text: "This is a paragraph"
---
kind: Paragraph
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: composition-test-paragraph
  namespace: krateo-system
spec:
  widgetData:
    text: "This is a test composition"