kind: YamlViewer
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: my-yaml-viewer
  namespace: test-namespace
spec:
  widgetData:
    json: '{"type":"object","additionalProperties":false,"properties":{"kind":{"type":"string","default":"YamlViewer"}}}'
