kind: NavMenuItem
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-datagrid-navmenuitem
  namespace: krateo-system
spec:
  widgetData:
    allowedResources:
      - pages
    resourceRefId: example-datagrid-page
    label: DataGrid
    icon: fa-grip
    path: /datagrid
  resourcesRefs:
    items:
      - id: example-datagrid-page
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-datagrid-page
        namespace: krateo-system
        resource: pages
        verb: GET
---
kind: Page
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-datagrid-page
  namespace: krateo-system
spec:
  widgetData:
    allowedResources:
      - barcharts
      - buttons
      - columns
      - datagrids
      - eventlists
      - filters
      - flowcharts
      - forms
      - linecharts
      - markdowns
      - panels
      - paragraphs
      - piecharts
      - rows
      - tables
      - tablists
      - yamlviewers
    items:
      - resourceRefId: example-datagrid-empty-panel
      - resourceRefId: example-datagrid-missing-resources-panel
      - resourceRefId: example-datagrid-single-list-panel
      - resourceRefId: example-datagrid-multiple-list-panel
      - resourceRefId: example-datagrid-multiple-default-panel
      - resourceRefId: example-datagrid-custom-grid-panel
      - resourceRefId: example-datagrid-with-prefix-panel
      - resourceRefId: example-datagrid-nested-panel
  resourcesRefs:
    items:
      - id: example-datagrid-empty-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-datagrid-empty-panel
        namespace: krateo-system
        resource: panels
        verb: GET  
      - id: example-datagrid-missing-resources-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-datagrid-missing-resources-panel
        namespace: krateo-system
        resource: panels
        verb: GET  
      - id: example-datagrid-single-list-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-datagrid-single-list-panel
        namespace: krateo-system
        resource: panels
        verb: GET 
      - id: example-datagrid-multiple-list-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-datagrid-multiple-list-panel
        namespace: krateo-system
        resource: panels
        verb: GET   
      - id: example-datagrid-multiple-default-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-datagrid-multiple-default-panel
        namespace: krateo-system
        resource: panels
        verb: GET  
      - id: example-datagrid-custom-grid-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-datagrid-custom-grid-panel
        namespace: krateo-system
        resource: panels
        verb: GET  
      - id: example-datagrid-with-prefix-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-datagrid-with-prefix-panel
        namespace: krateo-system
        resource: panels
        verb: GET    
      - id: example-datagrid-multiple-child-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-datagrid-multiple-child-panel
        namespace: krateo-system
        resource: panels
        verb: GET 
      - id: example-datagrid-nested-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-datagrid-nested-panel
        namespace: krateo-system
        resource: panels
        verb: GET 
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-datagrid-empty-panel
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: 'Case 1: Empty items array'
    items:
      - resourceRefId: example-datagrid-empty
  resourcesRefs:
    items:
      - id: example-datagrid-empty
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-datagrid-empty
        namespace: krateo-system
        resource: datagrids
        verb: GET  
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-datagrid-missing-resources-panel
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: 'Case 2: Missing resource references'
    items:
      - resourceRefId: example-datagrid-missing-resources
  resourcesRefs:
    items:
      - id: example-datagrid-missing-resources
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-datagrid-missing-resources
        namespace: krateo-system
        resource: datagrids
        verb: GET  
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-datagrid-single-list-panel
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: 'Case 3: Single child widget (list mode)'
    items:
      - resourceRefId: example-datagrid-single-list
  resourcesRefs:
    items:
      - id: example-datagrid-single-list
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-datagrid-single-list
        namespace: krateo-system
        resource: datagrids
        verb: GET 
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-datagrid-multiple-list-panel
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: 'Case 4: Multiple widgets in list mode'
    items:
      - resourceRefId: example-datagrid-multiple-list
  resourcesRefs:
    items:
      - id: example-datagrid-multiple-list
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-datagrid-multiple-list
        namespace: krateo-system
        resource: datagrids
        verb: GET 
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-datagrid-multiple-default-panel
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: 'Case 5: Multiple widgets in grid mode (default settings)'
    items:
      - resourceRefId: example-datagrid-multiple-default
  resourcesRefs:
    items:
      - id: example-datagrid-multiple-default
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-datagrid-multiple-default
        namespace: krateo-system
        resource: datagrids
        verb: GET 
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-datagrid-custom-grid-panel
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: 'Case 6: Custom grid configuration'
    items:
      - resourceRefId: example-datagrid-custom-grid
  resourcesRefs:
    items:
      - id: example-datagrid-custom-grid
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-datagrid-custom-grid
        namespace: krateo-system
        resource: datagrids
        verb: GET 
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-datagrid-with-prefix-panel
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: 'Case 7: Grid using prefix for contextual filtering'
    items:
      - resourceRefId: example-datagrid-with-prefix-filter
      - resourceRefId: example-datagrid-with-prefix
  resourcesRefs:
    items:
      - id: example-datagrid-with-prefix-filter
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-datagrid-with-prefix-filter
        namespace: krateo-system
        resource: filters
        verb: GET 
      - id: example-datagrid-with-prefix
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-datagrid-with-prefix
        namespace: krateo-system
        resource: datagrids
        verb: GET 
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-datagrid-nested-panel
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: 'Case 8: Nested data grid'
    items:
      - resourceRefId: example-datagrid-nested
  resourcesRefs:
    items:
      - id: example-datagrid-nested
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-datagrid-nested
        namespace: krateo-system
        resource: datagrids
        verb: GET 