kind: TabList
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: my-tab-list
  namespace: test-namespace
spec:
  widgetData:
    items:
      - label: first tab
        resourceRefId: first-column
      - label: second tab
        resourceRefId: second-column
  resourcesRefs:
    items:
      - id: first-column
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: first-column
        namespace: test-namespace
        resource: columns
        verb: GET
      - id: second-column
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: second-column
        namespace: test-namespace
        resource: columns
        verb: GET