kind: TabList
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: my-tab-list
  namespace: krateo-system
spec:
  widgetData:
    allowedResources:
      - barcharts
      - buttons
      - filters
      - flowcharts
      - linecharts
      - markdowns
      - paragraphs
      - piecharts
      - yamlviewers
    items:
      - label: first tab
        title: Ciao
        resourceRefId: my-panel
      - label: second tab
        resourceRefId: first-column
  resourcesRefs:
    items:
      - id: my-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: my-panel
        namespace: krateo-system
        resource: panels
        verb: GET
      - id: first-column
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: first-column
        namespace: krateo-system
        resource: columns
        verb: GET