kind: Row
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: first-row
  namespace: krateo-system
spec:
  widgetData:
    allowedResources:
      - barcharts
        buttons
        columns
        datagrids
        eventlists
        filters
        flowcharts
        forms
        linecharts
        markdowns
        panels
        paragraphs
        piecharts
        rows
        tables
        tablists
        yamlviewers
    items:
      - resourceRefId: table-of-pods
        size: 18
      - resourceRefId: pie-chart-inside-column
        size: 6
  resourcesRefs:
    items:
      - id: table-of-pods
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: table-of-pods
        namespace: krateo-system
        resource: tables
        verb: GET
      - id: pie-chart-inside-column
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: pie-chart-inside-column
        namespace: krateo-system
        resource: piecharts
        verb: GET
---
kind: Row
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: composition-test-row
  namespace: krateo-system
spec:
  widgetData:
    allowedResources:
      - barcharts
        buttons
        columns
        datagrids
        eventlists
        filters
        flowcharts
        forms
        linecharts
        markdowns
        panels
        paragraphs
        piecharts
        rows
        tables
        tablists
        yamlviewers
    items:
      - resourceRefId: composition-test-panel
  resourcesRefs:
    items:
      - id: composition-test-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: composition-test-panel
        namespace: krateo-system
        resource: panels
        verb: GET