kind: Row
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: first-row
  namespace: krateo-system
spec:
  widgetData:
    items:
      - resourceRefId: table-of-pods
      - resourceRefId: pie-chart-inside-column
  resourcesRefs:
    - id: table-of-pods
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: table-of-pods
      namespace: krateo-system
      resource: tables
      verb: GET
    - id: pie-chart-inside-column
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: pie-chart-inside-column
      namespace: krateo-system
      resource: piecharts
      verb: GET
---
kind: Row
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: composition-test-row
  namespace: krateo-system
spec:
  widgetData:
    items:
      - resourceRefId: composition-test-panel
  resourcesRefs:
    - id: composition-test-panel
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-test-panel
      namespace: krateo-system
      resource: panels
      verb: GET
