kind: Row
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: composition-test-row
  namespace: test-namespace
spec:
  widgetData:
    items:
      - resourceRefId: composition-test-panel
  resourcesRefs:
    items:
      - id: composition-test-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: composition-test-panel
        namespace: test-namespace
        resource: panels
        verb: GET