kind: NavMenuItem
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-paragraph-navmenuitem
  namespace: krateo-system
spec:
  widgetData:
    allowedResources:
      - pages
    resourceRefId: example-paragraph-page
    label: Paragraph
    icon: fa-paragraph
    path: /paragraph
  resourcesRefs:
    items:
      - id: example-paragraph-page
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-paragraph-page
        namespace: krateo-system
        resource: pages
        verb: GET
---
kind: Page
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-paragraph-page
  namespace: krateo-system
spec:
  widgetData:
    allowedResources:
      - barcharts
      - buttons
      - columns
      - datagrids
      - eventlists
      - filters
      - flowcharts
      - forms
      - linecharts
      - markdowns
      - panels
      - paragraphs
      - piecharts
      - rows
      - tables
      - tablists
      - yamlviewers
    items:
      - resourceRefId: example-paragraph-empty-panel
      - resourceRefId: example-paragraph-basic-panel
      - resourceRefId: example-paragraph-link-panel
      - resourceRefId: example-paragraph-multiline-panel
      - resourceRefId: example-paragraph-special-chars-panel
      - resourceRefId: example-paragraph-long-panel
  resourcesRefs:
    items:
      - id: example-paragraph-empty-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-paragraph-empty-panel
        namespace: krateo-system
        resource: panels
        verb: GET  
      - id: example-paragraph-basic-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-paragraph-basic-panel
        namespace: krateo-system
        resource: panels
        verb: GET  
      - id: example-paragraph-link-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-paragraph-link-panel
        namespace: krateo-system
        resource: panels
        verb: GET      
      - id: example-paragraph-multiline-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-paragraph-multiline-panel
        namespace: krateo-system
        resource: panels
        verb: GET       
      - id: example-paragraph-special-chars-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-paragraph-special-chars-panel
        namespace: krateo-system
        resource: panels
        verb: GET
      - id: example-paragraph-long-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-paragraph-long-panel
        namespace: krateo-system
        resource: panels
        verb: GET
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-paragraph-empty-panel
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: 'Case 1: Empty paragraph string'
    items:
      - resourceRefId: example-paragraph-empty
  resourcesRefs:
    items:
      - id: example-paragraph-empty
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-paragraph-empty
        namespace: krateo-system
        resource: paragraphs
        verb: GET  
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-paragraph-basic-panel
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: 'Case 2: Basic text'
    items:
      - resourceRefId: example-paragraph-basic
  resourcesRefs:
    items:
      - id: example-paragraph-basic
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-paragraph-basic
        namespace: krateo-system
        resource: paragraphs
        verb: GET
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-paragraph-link-panel
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: 'Case 3: Text with single link'
    items:
      - resourceRefId: example-paragraph-link
  resourcesRefs:
    items:
      - id: example-paragraph-link
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-paragraph-link
        namespace: krateo-system
        resource: paragraphs
        verb: GET
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-paragraph-multiline-panel
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: 'Case 4: Multiline text'
    items:
      - resourceRefId: example-paragraph-multiline
  resourcesRefs:
    items:
      - id: example-paragraph-multiline
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-paragraph-multiline
        namespace: krateo-system
        resource: paragraphs
        verb: GET  
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-paragraph-special-chars-panel
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: 'Case 5: Text containing special characters and pseudo-markdown'
    items:
      - resourceRefId: example-paragraph-special-chars
  resourcesRefs:
    items:
      - id: example-paragraph-special-chars
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-paragraph-special-chars
        namespace: krateo-system
        resource: paragraphs
        verb: GET  
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-paragraph-long-panel
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: 'Case 6: Long paragraph text'
    items:
      - resourceRefId: example-paragraph-long
  resourcesRefs:
    items:
      - id: example-paragraph-long
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-paragraph-long
        namespace: krateo-system
        resource: paragraphs
        verb: GET  