# Case 1: Empty paragraph string
# Target: intentionally empty paragraph content.
# Expected behavior: renders nothing (no placeholder), since empty string is a valid explicit input.
kind: Paragraph
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-paragraph-empty
  namespace: krateo-system
spec:
  widgetData:
    text: ""
---
# Case 2: Basic text
# Target: rendering simple text content without links or formatting.
# Expected behavior: displays plain paragraph inside <Typography.Paragraph>.
kind: Paragraph
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-paragraph-basic
  namespace: krateo-system
spec:
  widgetData:
    text: "This is a simple paragraph rendered using the Paragraph widget."
---
# Case 3: Text with single link
# Target: validate automatic link detection using Linkify.
# Expected behavior: URL is converted into clickable link opening in a new tab.
kind: Paragraph
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-paragraph-link
  namespace: krateo-system
spec:
  widgetData:
    text: "Visit https://krateo.io to learn more about Krateo PlatformOps."
---
# Case 4: Multiline text
# Target: check that line breaks are preserved and rendered correctly.
# Expected behavior: each line appears as a separate visual line in the paragraph.
kind: Paragraph
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-paragraph-multiline
  namespace: krateo-system
spec:
  widgetData:
    text: |
      This is the first line of the paragraph.
      Here is the second line with more details.
      And finally, the third line — all within one Paragraph widget.
---
# Case 5: Text containing special characters and pseudo-markdown
# Target: verify raw text handling with markdown-like syntax and symbols.
# Expected behavior: markdown-like symbols (*, _, #) are shown as plain text (no formatting).
kind: Paragraph
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-paragraph-special-chars
  namespace: krateo-system
spec:
  widgetData:
    text: "This text includes special characters: *stars*, _underscores_, #hash, and emoji 🚀 — all should render as plain text."
---
# Case 6: Long paragraph text
# Target: test overflow handling and wrapping behavior for large text blocks.
# Expected behavior: long content wraps properly within the container and remains scrollable if needed.
kind: Paragraph
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-paragraph-long
  namespace: krateo-system
spec:
  widgetData:
    text: >
      Krateo PlatformOps provides a powerful ecosystem for creating and managing digital products across multiple environments.
      It allows teams to define, automate, and observe applications using customizable widgets.
      This paragraph intentionally contains a long body of text to ensure that wrapping and layout behave correctly even with very large inputs.
