/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ButtonSchema {
  /**
   * kubernetes api version
   */
  apiVersion: "widgets.templates.krateo.io/v1alpha1";
  /**
   * name of the k8s Custom Resource
   */
  Kind: "Button";
  /**
   * kubernetes metadata
   */
  metadata: {
    namespace: string;
    name: string;
  };
  spec: {
    /**
     * the data that will be passed to the widget on the frontend
     */
    widgetData: {
      /**
       * the label of the button
       */
      label?: string;
      /**
       * the icon of the button (font awesome icon name eg: 'fa-inbox')
       */
      icon?: string;
      /**
       * the visual style of the button
       */
      type?: "default" | "text" | "link" | "primary" | "dashed";
    };
    /**
     * the actions of the button
     */
    actions?:
      | []
      | [
          {
            name: "onClick";
            type: "navigate";
            url: string;
            requireConfirmation?: boolean;
            loading?: "global" | "inline" | "none";
          }
        ];
  };
}
