/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DrawerSchema {
  /**
   * kubernetes api version
   */
  apiVersion: "widgets.templates.krateo.io/v1alpha1";
  /**
   * name of the k8s Custom Resource
   */
  Kind: "Drawer";
  /**
   * kubernetes metadata
   */
  metadata: {
    namespace: string;
    name: string;
  };
  spec: {
    widgetData: {
      /**
       * The widgets to be displayed inside the drawer
       */
      content: React.ReactNode;
      /**
       * Extra widgets to be displayed in the drawer header
       */
      extra?: React.ReactNode;
      /**
       * Widgets to be displayed in the drawer footer
       */
      footer?: React.ReactNode;
      /**
       * The size of the drawer
       */
      size: "default" | "large";
      /**
       * The title of the drawer
       */
      title: string;
      /**
       * The width of the drawer in pixels
       */
      width?: number;
    };
  };
}
