/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DrawerSchema {
  /**
   * kubernetes api version
   */
  apiVersion: "widgets.templates.krateo.io/v1alpha1";
  /**
   * name of the k8s Custom Resource
   */
  Kind: "Drawer";
  /**
   * kubernetes metadata
   */
  metadata: {
    namespace: string;
    name: string;
  };
  spec: {
    /**
     * the widgets to be displayed inside the drawer
     */
    content: {
      type: "Button";
      props: {};
    }[];
    /**
     * extra widgets to be displayed in the drawer header
     */
    extra?: {
      type: "Button";
      props: {};
    }[];
    /**
     * widgets to be displayed in the drawer footer
     */
    footer?: {
      type: "Button";
      props: {};
    }[];
    /**
     * the size of the drawer
     */
    size: "default" | "large";
    /**
     * the title of the drawer
     */
    title: string;
    /**
     * the width of the drawer in pixels
     */
    width?: number;
  };
}
