/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ParagraphSchema {
  kind: "Paragraph";
  apiVersion: "templates.krateo.io/v1alpha1";
  widgetData: {
    text: string;
  };
}
