/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ParagraphSchema {
  /**
   * kubernetes api version
   */
  apiVersion: "widgets.templates.krateo.io/v1alpha1";
  /**
   * name of the k8s Custom Resource
   */
  Kind: "Paragraph";
  /**
   * kubernetes metadata
   */
  metadata: {
    namespace: string;
    name: string;
  };
  spec: {
    /**
     * the data that will be passed to the widget on the frontend
     */
    widgetData: {
      /**
       * the content of the paragraph
       */
      text: string;
    };
  };
}
