kind: EventList
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: my-event-list
  namespace: krateo-system
spec:
  widgetData:
    events:
      - icon: "fa-exclamation-circle"
        reason: "FailedScheduling"
        message: "0/1 nodes are available: 1 Insufficient memory."
        type: "Warning"
        count: 3
        firstTimestamp: "2024-04-20T12:34:56Z"
        lastTimestamp: "2024-04-20T12:45:00Z"
        metadata:
          name: "my-pod.17d90d9c8ab2b1e1"
          namespace: "default"
          uid: "d1234567-89ab-4def-8123-abcdef012345"
          creationTimestamp: "2024-04-20T12:34:56Z"
        involvedObject:
          apiVersion: "v1"
          kind: "Pod"
          name: "my-pod"
          namespace: "default"
          uid: "abcd-1234"
        source:
          component: "scheduler"
      - icon: "fa-rocket"
        reason: "Started"
        message: "Started container nginx"
        type: "Normal"
        metadata:
          name: "nginx-pod.17d90d9c8ab2b1e2"
          namespace: "default"
          uid: "f1234567-89ab-4def-8123-abcdef012346"
          creationTimestamp: "2024-04-21T08:20:00Z"
        involvedObject:
          apiVersion: "v1"
          kind: "Pod"
          name: "nginx-pod"
          namespace: "default"
          uid: "defg-5678"
        source:
          component: "kubelet"
          host: "worker-node-1"
    prefix: filter-event-list
    sseEndpoint: "/events/stream"
    sseTopic: "k8s-event"
---
kind: Filters
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: event-list-filter
  namespace: krateo-system
spec:
  widgetData:
    prefix: filter-event-list
    fields:
      - label: Message
        name: 
        - message
        type: string
---
kind: Button
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: button-event-list-filter
  namespace: krateo-system
spec:
  widgetData:
    allowedResources:
    - barcharts
    - buttons
    - columns
    - datagrids
    - eventlists
    - filters
    - flowcharts
    - forms
    - linecharts
    - markdowns
    - pages
    - panels
    - paragraphs
    - piecharts
    - restactions
    - rows
    - tables
    - tablists
    - yamlviewers
    label: Filters
    icon: fa-rocket
    size: middle
    type: default
    clickActionId: open-event-list-filter
    actions:
      openDrawer:
        - id: open-event-list-filter
          resourceRefId: event-list-filter
          type: openDrawer
          title: Filter events
          size: large
  resourcesRefs:
    items:
      - id: event-list-filter
        apiVersion: widgets.templates.krateo.io/v1beta1
        resource: filters
        name: event-list-filter
        namespace: krateo-system
        verb: GET