kind: Page
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: dashboard-page
  namespace: krateo-system
spec:
  widgetData:
    allowedResources:
      - barcharts
      - buttons
      - columns
      - datagrids
      - eventlists
      - filters
      - flowcharts
      - forms
      - linecharts
      - markdowns
      - panels
      - paragraphs
      - piecharts
      - rows
      - tables
      - tablists
      - yamlviewers
    items:
      - resourceRefId: test-alignment-row
      - resourceRefId: test-alignment-row-in-panel
      - resourceRefId: panel-backend-endpoint-id
      - resourceRefId: button-filter-new-table
      - resourceRefId: test-updated-table
      - resourceRefId: test-navigate-page
      - resourceRefId: button-filter-table-fin-ops-test
      - resourceRefId: table-fin-ops-test
      - resourceRefId: panel-table-fin-ops-test
      - resourceRefId: panel-with-row
      - resourceRefId: panel-with-column
      - resourceRefId: button-with-drawer-backend-endpoint-id
  resourcesRefs:
    items:
      - id: test-alignment-row
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: test-alignment-row
        namespace: krateo-system
        resource: rows
        verb: GET  
      - id: test-alignment-row-in-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: test-alignment-row-in-panel
        namespace: krateo-system
        resource: panels
        verb: GET  
      - id: button-filter-new-table
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: button-filter-new-table
        namespace: krateo-system
        resource: buttons
        verb: GET  
      - id: test-updated-table
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: test-updated-table
        namespace: krateo-system
        resource: tables
        verb: GET
      - id: test-navigate-page
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: test-navigate-page
        namespace: krateo-system
        resource: buttons
        verb: GET
      - id: button-filter-table-fin-ops-test
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: button-filter-table-fin-ops-test
        namespace: krateo-system
        resource: buttons
        verb: GET  
      - id: table-fin-ops-test
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: table-fin-ops-test
        namespace: krateo-system
        resource: tables
        verb: GET  
      - id: panel-table-fin-ops-test
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: panel-table-fin-ops-test
        namespace: krateo-system
        resource: panels
        verb: GET  
      - id: panel-with-row
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: panel-with-row
        namespace: krateo-system
        resource: panels
        verb: GET
      - id: panel-with-column
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: panel-with-column
        namespace: krateo-system
        resource: panels
        verb: GET
      - id: panel-backend-endpoint-id
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: my-panel
        namespace: krateo-system
        resource: panels
        verb: GET
      - id: button-with-drawer-backend-endpoint-id
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: button-with-drawer
        namespace: krateo-system
        resource: buttons
        verb: GET
---
kind: Page
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: templates-page
  namespace: krateo-system
spec:
  widgetData:
    allowedResources:
      - barcharts
      - buttons
      - columns
      - datagrids
      - eventlists
      - filters
      - flowcharts
      - forms
      - linecharts
      - markdowns
      - panels
      - paragraphs
      - piecharts
      - rows
      - tables
      - tablists
      - yamlviewers
    items:
      - resourceRefId: button-delete-fireworks-app
      - resourceRefId: panel-paragraph
      - resourceRefId: panel-yaml-viewer
      - resourceRefId: panel-markdown
      - resourceRefId: panel-event-list
      - resourceRefId: panel-tab-list
      - resourceRefId: panel-line-chart
      - resourceRefId: panel-bar-chart
      - resourceRefId: panel-flow-chart
  resourcesRefs:
    items:
      - id: button-delete-fireworks-app
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: button-delete-fireworks-app
        namespace: krateo-system
        resource: buttons
        verb: GET
      - id: panel-paragraph
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: panel-paragraph
        namespace: krateo-system
        resource: panels
        verb: GET
      - id: panel-yaml-viewer
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: panel-yaml-viewer
        namespace: krateo-system
        resource: panels
        verb: GET
      - id: panel-markdown
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: panel-markdown
        namespace: krateo-system
        resource: panels
        verb: GET
      - id: panel-event-list
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: panel-event-list
        namespace: krateo-system
        resource: panels
        verb: GET
      - id: panel-tab-list
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: panel-tab-list
        namespace: krateo-system
        resource: panels
        verb: GET
      - id: panel-line-chart
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: panel-line-chart
        namespace: krateo-system
        resource: panels
        verb: GET
      - id: panel-bar-chart
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: panel-bar-chart
        namespace: krateo-system
        resource: panels
        verb: GET
      - id: panel-flow-chart
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: panel-flow-chart
        namespace: krateo-system
        resource: panels
        verb: GET
---
kind: Page
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: form-page
  namespace: krateo-system
spec:
  widgetData:
    allowedResources:
      - barcharts
      - buttons
      - columns
      - datagrids
      - eventlists
      - filters
      - flowcharts
      - forms
      - linecharts
      - markdowns
      - panels
      - paragraphs
      - piecharts
      - rows
      - tables
      - tablists
      - yamlviewers
    items:
      # - resourceRefId: test-firework-form
      - resourceRefId: button-with-drawer-form
      - resourceRefId: button-with-modal-form
      - resourceRefId: button-with-drawer-filters-2
      - resourceRefId: panel-grid
      - resourceRefId: composition-test-row
      - resourceRefId: test-panel
  resourcesRefs:
    items:
      # - id: test-firework-form
      #   apiVersion: widgets.templates.krateo.io/v1beta1
      #   name: test-firework-form
      #   namespace: krateo-system
      #   resource: forms
      #   verb: GET
      - id: button-with-drawer-form
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: button-with-drawer-form
        namespace: krateo-system
        resource: buttons
        verb: GET
      - id: button-with-modal-form
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: button-with-modal-form
        namespace: krateo-system
        resource: buttons
        verb: GET
      - id: button-with-drawer-filters-2
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: button-with-drawer-filters-2
        namespace: krateo-system
        resource: buttons
        verb: GET
      - id: panel-grid
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: panel-grid
        namespace: krateo-system
        resource: datagrids
        verb: GET
      - id: composition-test-row
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: composition-test-row
        namespace: krateo-system
        resource: rows
        verb: GET
      - id: test-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: test-panel
        namespace: krateo-system
        resource: panels
        verb: GET
---
# ---
# kind: Page
# apiVersion: widgets.templates.krateo.io/v1beta1
# metadata:
#   name: button-post-nginx
#   namespace: krateo-system
# spec:
#   widgetData:
#     items:
#       - resourceRefId: button-post-nginx
#   resourcesRefs:
#     items:
#       - id: button-post-nginx
#         apiVersion: widgets.templates.krateo.io/v1beta1
#         name: button-post-nginx
#         namespace: krateo-system
#         resource: buttons
#         verb: GET
# ---
kind: NavMenuItem
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: nav-menu-item-dashboard
  namespace: krateo-system
spec:
  widgetData:
    allowedResources:
      - pages
    resourceRefId: dashboard-page
    label: Dashboard
    icon: fa-chart-line
    path: /dashboard
    order: 10
  
  resourcesRefs:
    items:
      - id: dashboard-page
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: dashboard-page
        namespace: krateo-system
        resource: pages
        verb: GET
---
kind: NavMenuItem
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: nav-menu-item-templates
  namespace: krateo-system
spec:
  widgetData:
    allowedResources:
      - pages
    resourceRefId: templates-page
    label: Templates
    icon: fa-rectangle-list
    path: /templates
    order: 20

  resourcesRefs:
    items:
      - id: templates-page
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: templates-page
        namespace: krateo-system
        resource: pages
        verb: GET
---
kind: NavMenuItem
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: nav-menu-item-form
  namespace: krateo-system
spec:
  widgetData:
    allowedResources:
      - pages
    resourceRefId: form-page
    label: Form
    icon: fa-rectangle-list
    path: /form
    order: 50

  resourcesRefs:
    items:
      - id: form-page
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: form-page
        namespace: krateo-system
        resource: pages
        verb: GET
---
# kind: NavMenu
# apiVersion: widgets.templates.krateo.io/v1beta1
# metadata:
#   name: sidebar-nav-menu
#   namespace: krateo-system
# spec:
#   widgetData:
#     items: [] # TODO: compile this from restaction at the moment we are reading from resourcesRefs instead of items in the frontend
#   resourcesRefs:
#     items: []

#   resourcesRefsTemplate:
#     - iterator: ${ .navmenuitems }
#       template:
#         id: ${ .metadata.namespace + "_" + .metadata.name }
#         name: ${ .metadata.name }
#         apiVersion: ${ .apiVersion }
#         resource: navmenuitems
#         namespace: ${ .metadata.namespace }
#         verb: GET

#   apiRef:
#     name: navmenuitems
#     namespace: krateo-system
---
# apiVersion: templates.krateo.io/v1
# kind: RESTAction
# metadata:
#   name: navmenuitems
#   # namespace: {{ .Release.Namespace }}
#   namespace: krateo-system
# spec:
#   api:
#   - name: namespaces
#     path: "/api/v1/namespaces"
#     filter: "[.items[] | .metadata.name]"
#   - name: navmenuitems
#     dependsOn: 
#       name: namespaces
#       iterator: .[]
#     path: ${ "/apis/widgets.templates.krateo.io/v1beta1/namespaces/" + (.) + "/navmenuitems" }
#   filter: >
#     {
#       navmenuitems: (
#         [ .items[] ]
#         | sort_by(.spec.widgetData.order)
#       )
#     }
---


kind: NavMenu
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: sidebar-nav-menu
  namespace: krateo-system
spec:
  widgetData:
    allowedResources:
      - navmenuitems
    items: []
  resourcesRefs:
    items: []
  resourcesRefsTemplate:
    - iterator: ${ .navmenuitems }
      template:
        id: ${ .metadata.namespace + "_" + .metadata.name }
        name: ${ .metadata.name }
        apiVersion: ${ .apiVersion }
        resource: navmenuitems
        namespace: ${ .metadata.namespace }
        verb: GET
  apiRef:
    name: sidebar-nav-menu-items
    namespace: krateo-system
---
apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: sidebar-nav-menu-items
  namespace: krateo-system
spec:
  api:
  - name: namespaces
    path: "/api/v1/namespaces"
    filter: "[.namespaces.items[] | .metadata.name]"
  - name: navmenuitems
    continueOnError: true
    dependsOn: 
      name: namespaces
      iterator: .namespaces
    path: ${ "/apis/widgets.templates.krateo.io/v1beta1/namespaces/" + (.) + "/navmenuitems" }
  filter: >
    {
      navmenuitems: (
        if (.navmenuitems | type) == "array" then
          [.navmenuitems[]?.items[]?]
        elif (.navmenuitems | type) == "object" then
          [.navmenuitems.items[]?]
        else
          []
        end | sort_by(.spec.widgetData.order)
      )
    }
---
kind: NavMenuItem
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: nav-menu-item-grid
  namespace: krateo-system
spec:
  widgetData:
    allowedResources:
      - ciao
      - pages
    resourceRefId: grid-page
    label: Grid
    icon: fa-shapes
    path: /grid
    order: 30

  resourcesRefs:
    items:
      - id: grid-page
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: grid-page
        namespace: krateo-system
        resource: pages
        verb: GET
---
kind: Page
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: grid-page
  namespace: krateo-system
spec:
  widgetData:
    allowedResources:
      - barcharts
      - buttons
      - columns
      - datagrids
      - eventlists
      - filters
      - flowcharts
      - forms
      - linecharts
      - markdowns
      - panels
      - paragraphs
      - piecharts
      - rows
      - tables
      - tablists
      - yamlviewers
    items:
      - resourceRefId: button-with-drawer-filters
  resourcesRefs:
    items:
      - id: button-with-drawer-filters
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: button-with-drawer-filters
        namespace: krateo-system
        resource: buttons
        verb: GET
---
kind: NavMenuItem
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: nav-menu-item-table-filter
  namespace: krateo-system
spec:
  widgetData:
    allowedResources:
      - pages
    resourceRefId: table-filter-page
    label: Table filter
    icon: fa-shapes
    path: /tablefilter
    order: 30
  resourcesRefs:
    items:
      - id: table-filter-page
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: table-filter-page
        namespace: krateo-system
        resource: pages
        verb: GET
---
kind: Page
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: table-filter-page
  namespace: krateo-system
spec:
  widgetData:
    allowedResources:
      - barcharts
      - buttons
      - columns
      - datagrids
      - eventlists
      - filters
      - flowcharts
      - forms
      - linecharts
      - markdowns
      - panels
      - paragraphs
      - piecharts
      - rows
      - tables
      - tablists
      - yamlviewers
    items:
      - resourceRefId: table-filters
      # - resourceRefId: panel-with-column
      - resourceRefId: line-chart-with-dates
      - resourceRefId: line-chart-with-dates-2
  resourcesRefs:
    items:
      - id: table-filters
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: table-filters
        namespace: krateo-system
        resource: filters
        verb: GET
      # - id: panel-with-column
      #   apiVersion: widgets.templates.krateo.io/v1beta1
      #   name: panel-with-column
      #   namespace: krateo-system
      #   resource: panels
      #   verb: GET
      - id: line-chart-with-dates
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: line-chart-with-dates
        namespace: krateo-system
        resource: linecharts
        verb: GET
      - id: line-chart-with-dates-2
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: line-chart-with-dates-2
        namespace: krateo-system
        resource: linecharts
        verb: GET
