kind: Route
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: dashboard-route
  namespace: krateo-system
spec:
  widgetData:
    items:
      - resourceRefId: panel-with-row
      - resourceRefId: panel-with-column
      - resourceRefId: panel-backend-endpoint-id
      - resourceRefId: button-3-backend-endpoint-id
      - resourceRefId: button-with-drawer-backend-endpoint-id
  resourcesRefs:
    - id: panel-with-row
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: panel-with-row
      namespace: krateo-system
      resource: panels
      verb: GET
    - id: panel-with-column
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: panel-with-column
      namespace: krateo-system
      resource: panels
      verb: GET
    - id: panel-backend-endpoint-id
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: my-panel
      namespace: krateo-system
      resource: panels
      verb: GET
    - id: button-3-backend-endpoint-id
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: button-3
      namespace: krateo-system
      resource: buttons
      verb: GET
    - id: button-with-drawer-backend-endpoint-id
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: button-with-drawer
      namespace: krateo-system
      resource: buttons
      verb: GET
---
kind: Route
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: templates-route
  namespace: krateo-system
spec:
  widgetData:
    items:
      - resourceRefId: button-delete-fireworks-app
      - resourceRefId: panel-paragraph
      - resourceRefId: panel-yaml-viewer
      - resourceRefId: panel-event-list
      - resourceRefId: panel-tab-list
      - resourceRefId: panel-line-chart
      - resourceRefId: panel-bar-chart
  resourcesRefs:
    - id: button-delete-fireworks-app
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: button-delete-fireworks-app
      namespace: krateo-system
      resource: buttons
      verb: GET
    - id: panel-paragraph
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: panel-paragraph
      namespace: krateo-system
      resource: panels
      verb: GET
    - id: panel-yaml-viewer
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: panel-yaml-viewer
      namespace: krateo-system
      resource: panels
      verb: GET
    - id: panel-event-list
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: panel-event-list
      namespace: krateo-system
      resource: panels
      verb: GET
    - id: panel-tab-list
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: panel-tab-list
      namespace: krateo-system
      resource: panels
      verb: GET
    - id: panel-line-chart
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: panel-line-chart
      namespace: krateo-system
      resource: panels
      verb: GET
    - id: panel-bar-chart
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: panel-bar-chart
      namespace: krateo-system
      resource: panels
      verb: GET
---
kind: Route
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: compositions-route
  namespace: krateo-system
spec:
  widgetData:
    items:
      - resourceRefId: composition-test-row
  resourcesRefs:
    - id: composition-test-row
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-test-row
      namespace: krateo-system
      resource: rows
      verb: GET
---
kind: Route
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: form-route
  namespace: krateo-system
spec:
  widgetData:
    items:
      - resourceRefId: button-with-drawer-form
  resourcesRefs:
    - id: button-with-drawer-form
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: button-with-drawer-form
      namespace: krateo-system
      resource: buttons
      verb: GET
---
# ---
# kind: Route
# apiVersion: widgets.templates.krateo.io/v1beta1
# metadata:
#   name: button-post-nginx
#   namespace: krateo-system
# spec:
#   widgetData:
#     items:
#       - resourceRefId: button-post-nginx
#   resourcesRefs:
#     - id: button-post-nginx
#       apiVersion: widgets.templates.krateo.io/v1beta1
#       name: button-post-nginx
#       namespace: krateo-system
#       resource: buttons
#       verb: GET
# ---
kind: NavMenuItem
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: nav-menu-item-dashboard
  namespace: krateo-system
spec:
  widgetData:
    resourceRefId: dashboard-route
    label: Dashboard
    icon: fa-chart-line
    path: /dashboard
  
  resourcesRefs:
    - id: dashboard-route
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: dashboard-route
      namespace: krateo-system
      resource: routes
      verb: GET
---
kind: NavMenuItem
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: nav-menu-item-templates
  namespace: krateo-system
spec:
  widgetData:
    resourceRefId: templates-route
    label: Templates
    icon: fa-rectangle-list
    path: /templates

  resourcesRefs:
    - id: templates-route
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: templates-route
      namespace: krateo-system
      resource: routes
      verb: GET
---
kind: NavMenuItem
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: nav-menu-item-form
  namespace: krateo-system
spec:
  widgetData:
    resourceRefId: form-route
    label: Form
    icon: fa-rectangle-list
    path: /form

  resourcesRefs:
    - id: form-route
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: form-route
      namespace: krateo-system
      resource: routes
      verb: GET
---
kind: NavMenuItem
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: nav-menu-item-compositions
  namespace: krateo-system
spec:
  widgetData:
    resourceRefId: compositions-route
    label: Compositions
    icon: fa-shapes
    path: /compositions

  resourcesRefs:
    - id: compositions-route
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: compositions-route
      namespace: krateo-system
      resource: routes
      verb: GET
---
kind: NavMenu
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: sidebar-nav-menu
  namespace: krateo-system
spec:
  widgetData:
    items: [] # TODO: compile this from restaction at the moment we are reading from resourcesRefs instead of items in the frontend
  resourcesRefs: []

  resourcesRefsTemplate:
    - iterator: ${ .navmenuitems }
      template:
        id: ${ .metadata.namespace + "_" + .metadata.name }
        name: ${ .metadata.name }
        apiVersion: ${ .apiVersion }
        resource: navmenuitems
        namespace: ${ .metadata.namespace }
        verb: GET

  apiRef:
    name: navmenuitems
    namespace: krateo-system
---
apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: navmenuitems
  # namespace: {{ .Release.Namespace }}
  namespace: krateo-system
spec:
  api:
  - name: namespaces
    path: "/api/v1/namespaces"
    filter: "[.items[] | .metadata.name]"
  - name: navmenuitems
    continueOnError: true
    dependsOn: 
      name: namespaces
      iterator: .[]
    path: ${ "/apis/widgets.templates.krateo.io/v1beta1/namespaces/" + (.) + "/navmenuitems" }
  filter: "{navmenuitems: [.navmenuitems[] | select(.items != null) | .items[]]}"
    
    
    