kind: Route
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: dashboard-route
  namespace: krateo-system
spec:
  widgetData:
    label: Dashboard
    path: /dashboard
    icon: fa-chart-line
    backendEndpointId: my-panel
  
  backendEndpoints:
    - id: my-panel
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: my-panel
      namespace: krateo-system
      resource: panels
      verb: GET
---
kind: NavMenu
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: sidebar-nav-menu
  namespace: krateo-system
spec:
  widgetData:
    items:
      - backendEndpointId: dashboard-route
  backendEndpoints:
    - id: dashboard-route
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: dashboard-route
      namespace: krateo-system
      resource: routes
      verb: GET