kind: Route
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: dashboard-route
  namespace: krateo-system
spec:
  widgetData:
    items:
      - resourceRefId: panel-with-row
      - resourceRefId: panel-with-column
      - resourceRefId: panel-backend-endpoint-id
      - resourceRefId: button-3-backend-endpoint-id
      - resourceRefId: button-with-drawer-backend-endpoint-id
  resourcesRefs:
    - id: panel-with-row
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: panel-with-row
      namespace: krateo-system
      resource: panels
      verb: GET
    - id: panel-with-column
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: panel-with-column
      namespace: krateo-system
      resource: panels
      verb: GET
    - id: panel-backend-endpoint-id
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: my-panel
      namespace: krateo-system
      resource: panels
      verb: GET
    - id: button-3-backend-endpoint-id
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: button-3
      namespace: krateo-system
      resource: buttons
      verb: GET
    - id: button-with-drawer-backend-endpoint-id
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: button-with-drawer
      namespace: krateo-system
      resource: buttons
      verb: GET
---
kind: Route
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: templates-route
  namespace: krateo-system
spec:
  widgetData:
    items:
      - resourceRefId: panel-paragraph
      - resourceRefId: panel-yaml-viewer
      - resourceRefId: panel-event-list
      - resourceRefId: panel-tab-list
      - resourceRefId: panel-line-chart
      - resourceRefId: panel-bar-chart
  resourcesRefs:
    - id: panel-paragraph
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: panel-paragraph
      namespace: krateo-system
      resource: panels
      verb: GET
    - id: panel-yaml-viewer
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: panel-yaml-viewer
      namespace: krateo-system
      resource: panels
      verb: GET
    - id: panel-event-list
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: panel-event-list
      namespace: krateo-system
      resource: panels
      verb: GET
    - id: panel-tab-list
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: panel-tab-list
      namespace: krateo-system
      resource: panels
      verb: GET
    - id: panel-line-chart
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: panel-line-chart
      namespace: krateo-system
      resource: panels
      verb: GET
    - id: panel-bar-chart
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: panel-bar-chart
      namespace: krateo-system
      resource: panels
      verb: GET
---
kind: Route
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: compositions-route
  namespace: krateo-system
spec:
  widgetData:
    items:
      - resourceRefId: composition-test-row
  resourcesRefs:
    - id: composition-test-row
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-test-row
      namespace: krateo-system
      resource: rows
      verb: GET
---
kind: Route
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: nginx-form-route
  namespace: krateo-system
spec:
  widgetData:
    items:
      - resourceRefId: nginx-form-panel
  resourcesRefs:
    - id: nginx-form-panel
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: nginx-form-panel
      namespace: krateo-system
      resource: panels
      verb: GET
---
kind: Route
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: button-post-nginx
  namespace: krateo-system
spec:
  widgetData:
    items:
      - resourceRefId: button-post-nginx
  resourcesRefs:
    - id: button-post-nginx
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: button-post-nginx
      namespace: krateo-system
      resource: buttons
      verb: GET
---
kind: NavMenu
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: sidebar-nav-menu
  namespace: krateo-system
spec:
  widgetData:
    items:
      - resourceRefId: dashboard-route
        label: Dashboard
        icon: fa-chart-line
        path: /dashboard
      - resourceRefId: templates-route
        label: Templates
        icon: fa-rectangle-list
        path: /templates
      - resourceRefId: compositions-route
        label: Compositions
        icon: fa-shapes
        path: /compositions
      - resourceRefId: nginx-form-route
        label: Nginx factory
        icon: fa-shapes
        path: /nginx
      - resourceRefId: button-post-nginx
        label: Post button
        icon: fa-rocket
        path: /post-button
  resourcesRefs:
    - id: dashboard-route
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: dashboard-route
      namespace: krateo-system
      resource: routes
      verb: GET
    - id: templates-route
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: templates-route
      namespace: krateo-system
      resource: routes
      verb: GET
    - id: compositions-route
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: compositions-route
      namespace: krateo-system
      resource: routes
      verb: GET
    - id: nginx-form-route
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: nginx-form-route
      namespace: krateo-system
      resource: routes
      verb: GET
    - id: button-post-nginx
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: button-post-nginx
      namespace: krateo-system
      resource: routes
      verb: GET
    
