kind: Table
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: table-of-namespaces
  namespace: krateo-system
spec:

  widgetData:
    allowedResources:
      - barcharts
        buttons
        filters
        flowcharts
        linecharts
        markdowns
        paragraphs
        piecharts
        yamlviewers
    pageSize: 10
    data: []
    columns:
      - valueKey: name
        title: Cluster Namespaces

  widgetDataTemplate:
    - forPath: data
      expression: ${ .namespaces }
  apiRef:
    name: cluster-namespaces
    namespace: krateo-system


---
apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: cluster-namespaces
  namespace: krateo-system
spec:
  api:
    - name: namespaces
      path: "/api/v1/namespaces"
      filter: >
        [.items[] 
          | [
              {
                valueKey: "name",
                kind: "jsonSchemaType",
                type: "string",
                stringValue: .metadata.name
              }
            ]
        ]
