kind: Table
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: my-table
  namespace: test-namespace
spec:
  widgetData:
    pageSize: 10
    data: 
      - name: Alice
        age: 30
        icon: fa-rocket
      - name: Bob
        age: 45
        icon: fa-exclamation-circle
    columns:
      - valueKey: name
        title: Name
      - valueKey: age
        title: Age
      - valueKey: icon
        title: Icon
        kind: icon
        color: red