kind: Table
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: table-of-pods
  namespace: krateo-system
spec:
  widgetData:
    pageSize: 10
    data: []
    columns:
      - valueKey: name
        title: Pod Name
      - valueKey: namespace
        color: orange
        title: Namespace
      - valueKey: image
        title: Image
      - valueKey: testIcon
        color: red
        title: Test icon
        kind: icon

  widgetDataTemplate:
    - forPath: data
      expression: ${ .pods }
  apiRef:
    name: cluster-pods
    namespace: krateo-system


---
apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: cluster-pods
  namespace: krateo-system
spec:
  api:
  - name: pods
    path: "/api/v1/pods"
    filter: "[.items[] | {key: .metadata.name, name: .metadata.name, namespace: .metadata.namespace, image: .spec.containers[0].image, testIcon: \"fa-rocket\"}]"