kind: Table
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: my-table
  namespace: test-namespace
spec:
  widgetData:
    allowedResources:
      - barcharts
      - buttons
      - filters
      - flowcharts
      - linecharts
      - markdowns
      - paragraphs
      - piecharts
      - yamlviewers
    pageSize: 10
    data: 
      - 
        - valueKey: name
          kind: jsonSchemaType
          type: string
          stringValue: Alice
        - valueKey: age
          kind: jsonSchemaType
          type: integer
          numberValue: 30
        - valueKey: icon
          kind: icon
          stringValue: fa-rocket

      - 
        - valueKey: name
          kind: jsonSchemaType
          type: string
          stringValue: Bob
        - valueKey: age
          kind: jsonSchemaType
          type: integer
          numberValue: 45
        - valueKey: icon
          kind: icon
          stringValue: fa-exclamation-circle

    columns:
      - valueKey: name
        title: Name
      - valueKey: age
        title: Age
      - valueKey: icon
        title: Icon
        kind: icon
        color: red
