kind: Button
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: button-filter-table-fin-ops-test
  namespace: krateo-system
spec:
  widgetData:
    label: Filters
    icon: fa-rocket
    size: middle
    type: default
    clickActionId: action-filter-table-fin-ops-test
    actions:
      openDrawer:
        - id: action-filter-table-fin-ops-test
          resourceRefId: filter-table-fin-ops-test
          type: openDrawer
          title: Filter compositions
          size: large
  resourcesRefs:
    items:
      - id: filter-table-fin-ops-test
        apiVersion: widgets.templates.krateo.io/v1beta1
        resource: filters
        name: filter-table-fin-ops-test
        namespace: krateo-system
        verb: GET
---
kind: Filters
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: filter-table-fin-ops-test
  namespace: krateo-system
spec:
  widgetData:
    prefix: filter-table-fin-ops-test
    fields:
      - label: composition name
        name: 
        - releaseName
        type: string
---
kind: Table
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: table-fin-ops-test
  namespace: krateo-system
spec:
  widgetData:
    allowedResources:
      - barcharts
      - buttons
      - filters
      - flowcharts
      - linecharts
      - markdowns
      - paragraphs
      - piecharts
      - yamlviewers
    columns:
      - valueKey: releaseName
        title: Name
      - valueKey: namespace
        title: Namespace
      - valueKey: appVersion
        title: App Version
      - valueKey: chartVersion
        title: Chart Version
      - valueKey: revision
        title: Revision
      - valueKey: status
        title: Status
      - valueKey: updated
        title: Last Update
    data:
      - - valueKey: releaseName
          kind: jsonSchemaType
          type: string
          stringValue: test
      - - valueKey: appVersion
          kind: jsonSchemaType
          type: string
          stringValue: "9.0.1"
        - valueKey: chartVersion
          kind: jsonSchemaType
          type: string
          stringValue: "0.1.0"
        - valueKey: namespace
          kind: jsonSchemaType
          type: string
          stringValue: krateo-system
        - valueKey: releaseName
          kind: jsonSchemaType
          type: string
          stringValue: opa-kube-mgmt
        - valueKey: revision
          kind: jsonSchemaType
          type: integer
          numberValue: 15
        - valueKey: status
          kind: jsonSchemaType
          type: string
          stringValue: deployed
        - valueKey: updated
          kind: jsonSchemaType
          type: string
          stringValue: "2025-08-18T15:22:07Z"
      - - valueKey: appVersion
          kind: jsonSchemaType
          type: string
          stringValue: "0.1.0"
        - valueKey: chartVersion
          kind: jsonSchemaType
          type: string
          stringValue: "0.1.0"
        - valueKey: namespace
          kind: jsonSchemaType
          type: string
          stringValue: krateo-system
        - valueKey: releaseName
          kind: jsonSchemaType
          type: string
          stringValue: finops-moving-window-policy
        - valueKey: revision
          kind: jsonSchemaType
          type: integer
          numberValue: 15
        - valueKey: status
          kind: jsonSchemaType
          type: string
          stringValue: deployed
        - valueKey: updated
          kind: jsonSchemaType
          type: string
          stringValue: "2025-08-18T15:22:04Z"
    pageSize: 10
    prefix: filter-table-fin-ops-test
