kind: RoutesLoader
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: routes-loader
  namespace: krateo-v2-system
spec:
  widgetData: {}
  resourcesRefs: []

  resourcesRefsTemplate:
    - iterator: ${ .routes }
      template:
        id: ${ .metadata.namespace + "_" + .metadata.name }
        name: ${ .metadata.name }
        apiVersion: ${ .apiVersion }
        resource: routes
        namespace: ${ .metadata.namespace }
        verb: GET

  apiRef:
    name: all-routes
    namespace: krateo-v2-system
---
apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: all-routes
  namespace: krateo-v2-system
spec:
  api:
  - name: namespaces
    path: "/api/v1/namespaces"
    filter: "[.items[] | .metadata.name]"
  - name: routes
    continueOnError: true
    dependsOn: 
      name: namespaces
      iterator: .[]
    path: ${ "/apis/widgets.templates.krateo.io/v1beta1/namespaces/" + (.) + "/routes" }
  filter: "{routes: [.routes[] | select(.items != null) | .items[]]}"