kind: DataGrid
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: dashboard-grid
  namespace: krateo-system
spec:
  widgetData:
    prefix: filters-sample
    asGrid: true
    items:
      - resourceRefId: my-panel
      - resourceRefId: panel-with-column
      - resourceRefId: panel-paragraph
  resourcesRefs:
    - id: my-panel
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: my-panel
      namespace: krateo-system
      resource: panels
      verb: GET
    - id: panel-with-column
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: panel-with-column
      namespace: krateo-system
      resource: panels
      verb: GET
    - id: panel-paragraph
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: panel-paragraph
      namespace: krateo-system
      resource: panels
      verb: GET
---
kind: DataGrid
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: compositions-grid
  namespace: krateo-system
spec:
  widgetData:
    prefix: filters-sample
    asGrid: true
    grid:
      column: 2
      gutter: 16
    items:
      - resourceRefId: composition-filtrable-card-1
      - resourceRefId: composition-filtrable-card-2
      - resourceRefId: composition-filtrable-card-3
      - resourceRefId: composition-filtrable-card-4
      - resourceRefId: composition-filtrable-card-5
  resourcesRefs:
    - id: composition-filtrable-card-1
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-filtrable-card-1
      namespace: krateo-system
      resource: compositioncards
      verb: GET
    - id: composition-filtrable-card-2
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-filtrable-card-2
      namespace: krateo-system
      resource: compositioncards
      verb: GET
    - id: composition-filtrable-card-3
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-filtrable-card-3
      namespace: krateo-system
      resource: compositioncards
      verb: GET
    - id: composition-filtrable-card-4
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-filtrable-card-4
      namespace: krateo-system
      resource: compositioncards
      verb: GET
    - id: composition-filtrable-card-5
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-filtrable-card-5
      namespace: krateo-system
      resource: compositioncards
      verb: GET
---
kind: DataGrid
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: panel-grid
  namespace: krateo-system
spec:
  widgetData:
    prefix: panel-filters
    asGrid: true
    grid:
      column: 1
      gutter: 16
    items:
      - resourceRefId: fireworksapp-template-panel-schema-notordered
      - resourceRefId: fireworksapp-template-panel-schema-notordered-2
  resourcesRefs:
    - id: fireworksapp-template-panel-schema-notordered
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: fireworksapp-template-panel-schema-notordered
      namespace: krateo-system
      resource: panels
      verb: GET
    - id: fireworksapp-template-panel-schema-notordered-2
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: fireworksapp-template-panel-schema-notordered-2
      namespace: krateo-system
      resource: panels
      verb: GET