kind: Page
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: compositions-route
  namespace: test-namespace
spec:
  widgetData:
    allowedResources:
      - barcharts
      - buttons
      - columns
      - datagrids
      - eventlists
      - filters
      - flowcharts
      - forms
      - linecharts
      - markdowns
      - panels
      - paragraphs
      - piecharts
      - rows
      - tables
      - tablists
      - yamlviewers
    items:
      - resourceRefId: composition-test-item
  resourcesRefs:
    items:
      - id: composition-test-item
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: composition-test-item
        namespace: test-namespace
        resource: nav
        verb: GET