kind: Page
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: compositions-route
  namespace: test-namespace
spec:
  widgetData:
    items:
      - resourceRefId: composition-test-row
  resourcesRefs:
    - id: composition-test-row
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: composition-test-row
      namespace: test-namespace
      resource: rows
      verb: GET