kind: NavMenuItem
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-column-navmenuitem
  namespace: krateo-system
spec:
  widgetData:
    allowedResources:
      - pages
    resourceRefId: example-column-page
    label: Column
    icon: fa-table-columns
    path: /column
  resourcesRefs:
    items:
      - id: example-column-page
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-column-page
        namespace: krateo-system
        resource: pages
        verb: GET
---
kind: Page
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-column-page
  namespace: krateo-system
spec:
  widgetData:
    allowedResources:
      - barcharts
      - buttons
      - columns
      - datagrids
      - eventlists
      - filters
      - flowcharts
      - forms
      - linecharts
      - markdowns
      - panels
      - paragraphs
      - piecharts
      - rows
      - tables
      - tablists
      - yamlviewers
    items:
      - resourceRefId: example-column-empty-panel
      - resourceRefId: example-column-missing-ref-panel
      - resourceRefId: example-column-zero-size-panel
      - resourceRefId: example-column-single-child-panel
      - resourceRefId: example-column-single-child-full-screen-panel
      - resourceRefId: example-column-mixed-panel
      - resourceRefId: example-column-multiple-child-panel
      - resourceRefId: example-column-nested-panel
  resourcesRefs:
    items:
      - id: example-column-empty-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-column-empty-panel
        namespace: krateo-system
        resource: panels
        verb: GET  
      - id: example-column-missing-ref-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-column-missing-ref-panel
        namespace: krateo-system
        resource: panels
        verb: GET  
      - id: example-column-zero-size-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-column-zero-size-panel
        namespace: krateo-system
        resource: panels
        verb: GET   
      - id: example-column-single-child-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-column-single-child-panel
        namespace: krateo-system
        resource: panels
        verb: GET  
      - id: example-column-single-child-full-screen-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-column-single-child-full-screen-panel
        namespace: krateo-system
        resource: panels
        verb: GET  
      - id: example-column-mixed-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-column-mixed-panel
        namespace: krateo-system
        resource: panels
        verb: GET    
      - id: example-column-multiple-child-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-column-multiple-child-panel
        namespace: krateo-system
        resource: panels
        verb: GET 
      - id: example-column-nested-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-column-nested-panel
        namespace: krateo-system
        resource: panels
        verb: GET 
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-column-empty-panel
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: 'Case 1: Empty items array'
    items:
      - resourceRefId: example-column-empty
  resourcesRefs:
    items:
      - id: example-column-empty
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-column-empty
        namespace: krateo-system
        resource: columns
        verb: GET  
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-column-missing-ref-panel
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: 'Case 2: Missing resource resolution'
    items:
      - resourceRefId: example-column-missing-ref
  resourcesRefs:
    items:
      - id: example-column-missing-ref
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-column-missing-ref
        namespace: krateo-system
        resource: columns
        verb: GET  
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-column-zero-size-panel
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: 'Case 3: Zero-sized column'
    items:
      - resourceRefId: example-column-zero-size
  resourcesRefs:
    items:
      - id: example-column-zero-size
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-column-zero-size
        namespace: krateo-system
        resource: columns
        verb: GET 
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-column-single-child-panel
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: 'Case 4: Single child'
    items:
      - resourceRefId: example-column-single-child
  resourcesRefs:
    items:
      - id: example-column-single-child
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-column-single-child
        namespace: krateo-system
        resource: columns
        verb: GET 
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-column-single-child-full-screen-panel
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: 'Case 5: Single child full screen'
    items:
      - resourceRefId: example-column-single-child-full-screen
  resourcesRefs:
    items:
      - id: example-column-single-child-full-screen
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-column-single-child-full-screen
        namespace: krateo-system
        resource: columns
        verb: GET 
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-column-mixed-panel
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: 'Case 6: Mixed valid and invalid children'
    items:
      - resourceRefId: example-column-mixed
  resourcesRefs:
    items:
      - id: example-column-mixed
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-column-mixed
        namespace: krateo-system
        resource: columns
        verb: GET 
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-column-multiple-child-panel
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: 'Case 7: Multiple child widgets'
    items:
      - resourceRefId: example-column-multiple-child
  resourcesRefs:
    items:
      - id: example-column-multiple-child
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-column-multiple-child
        namespace: krateo-system
        resource: columns
        verb: GET 
---
kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-column-nested-panel
  namespace: krateo-system
spec:
  widgetData:
    actions: {}
    title: 'Case 8: Nested columns'
    items:
      - resourceRefId: example-column-nested
  resourcesRefs:
    items:
      - id: example-column-nested
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: example-column-nested
        namespace: krateo-system
        resource: columns
        verb: GET 