kind: Button
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: simple-guide-button
  namespace: simple-guide
spec:
  widgetData:
    icon: fa-sun
    label: I open a drawer with a form
    clickActionId: openDrawer-action-id # <- this needs to match the id of an action declared below in spec.actions
    actions: 
      openDrawer:
        - id: openDrawer-action-id 
          resourceRefId: form-id # <- this needs to match the id of a resource declared below in spec.resourcesRefs
          type: openDrawer
          title: Composition form
          size: large

  resourcesRefs:
    items:
      - id: form-id
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: simple-guide-form
        namespace: simple-guide
        resource: forms
        verb: GET
---
kind: Form
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: simple-guide-form
  namespace: simple-guide
spec:
  widgetData:
    stringSchema: |
      {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "title": "Pod Name",
            "description": "The name of your Nginx pod"
          }
        },
        "required": ["name"]
      }
    
    submitActionId: submit-action-id
    actions:
      rest:
        - id: submit-action-id
          resourceRefId: resource-ref-1
          type: rest
          payloadKey: spec
          payloadToOverride:
            - name: metadata.name
              value: ${ name }
          payload:
            apiVersion: v1
            kind: Pod
            metadata:
              name: "aa"
            spec:
              containers:
                - image: 'nginx:latest'
                  name: nginx
                  ports:
                    - containerPort: 80

  resourcesRefs:
    items:
      - id: resource-ref-1
        apiVersion: v1
        resource: pods
        name: my-pod-name
        namespace: krateo-system
        verb: POST
