kind: Button
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: simple-guide-button
  namespace: krateo-system
spec:
  widgetData:
    icon: fa-sun
    label: I open a drawer with a form
    clickActionId: openDrawer-action-id
    actions: 
      openDrawer:
        - id: openDrawer-action-id 
          resourceRefId: form-id
          type: openDrawer
          title: Composition form
          size: large
  resourcesRefs:
    items:
      - id: form-id
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: simple-guide-form
        namespace: krateo-system
        resource: forms
        verb: GET
---
kind: Form
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: simple-guide-form
  namespace: krateo-system
spec:
  widgetData:
    stringSchema: |
      {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "title": "Pod Name",
            "description": "The name of your Nginx pod"
          }
        },
        "required": ["name"]
      }
    submitActionId: create-action-guide-pod
    actions:
      rest:
        - id: create-action-guide-pod
          type: rest
          resourceRefId: create-action-guide-pod
          payload:
            apiVersion: v1
            kind: Pod
            metadata:
              name: action-guide-pod
            spec:
              containers:
                - name: demo
                  image: nginx:latest
          payloadToOverride:
            - name: metadata.name
              value: ${ .json.name }
          headers:
            - "Content-Type: application/json"
  resourcesRefs:
    items:
      - id: create-action-guide-pod
        apiVersion: v1
        resource: pods
        name: action-guide-pod
        namespace: krateo-system
        verb: POST
