kind: Button
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: simple-guide-button
  namespace: krateo-system
spec:
  widgetData:
    icon: fa-sun
    label: I was updated!
    clickActionId: openDrawer-action-id
    actions: 
      openDrawer:
        - id: openDrawer-action-id 
          resourceRefId: paragraph-id
          type: openDrawer
          title: Drawer with paragraph
          size: large
  resourcesRefs:
    items:
      - id: paragraph-id
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: simple-guide-paragraph
        namespace: krateo-system
        resource: paragraphs
        verb: GET
---
kind: Paragraph
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: simple-guide-paragraph
  namespace: krateo-system
spec:
  widgetData:
    text: "This is a paragraph"