---
apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  annotations:
    "krateo.io/verbose": "false"
  name: list-buttons
  namespace: demo-system
spec:
  api:
  - name: paginatedButtons
    continueOnError: true
    errorKey: pagination-buttons-error
    path: ${ "/apis/widgets.templates.krateo.io/v1beta1/namespaces/demo-system/buttons" }
    filter: |
      .buttons.items as $items
      | ._slice_.offset as $offset
      | ._slice_.perPage as $perPage
      | [$items
        | length as $len
        | range($offset; $offset + $perPage)
        | select(. < $len)       # <-- evita out-of-bounds
        | $items[.]]