kind: Filters
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: my-filters
  namespace: krateo-system
spec:
  widgetData:
    prefix: filters-sample
    fields:
      - label: composition name
        name: 
        - title
        type: string
      - label: date range
        name: 
        - date
        type: daterange
      - label: tag
        name:
        - tags
        type: string
      - label: status
        name: 
        - status
        type: string
        options:
          - active
          - pending
          - disabled
---
kind: Filters
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: table-filters
  namespace: krateo-system
spec:
  widgetData:
    prefix: filters-pods
    fields:
      - label: pod name
        name: 
        - name # Column name
        type: string
      - label: pod image
        name:
        - image # Column name
        type: string
      # - label: table to filter
        # name: title
        # type: date
      - label: period
        name:
          - date
          - xAxis
        type: daterange

---
kind: Filters
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: dashboard-filters
  namespace: krateo-system
spec:
  widgetData:
    prefix: filters-dashboard
    fields:
      - label: date range
        name: 
        - date
        - xAxis
        type: daterange
---
kind: Filters
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: panel-filters
  namespace: krateo-system
spec:
  widgetData:
    prefix: panel-filters
    fields:
      - label: Title
        name:
        - title
        type: string
